/* Approved research context: isolated controller, no inline handlers or remote assets. */
(() => {
  'use strict';
  if (window.__beeResearchContext) return;
  window.__beeResearchContext = true;
  const COPY = {
    fa: ['زمینهٔ کسب‌وکار در تحلیل','اتصال کسب‌وکار به‌تنهایی تحلیل یا انتشار را تغییر نمی‌دهد.','تنظیم و پیش‌نمایش','روش فعلی بدون تغییر','منبع اطلاعات','بدون کسب‌وکار','کسب‌وکار محلی','کسب‌وکار متصل از Contenter','روش تحلیل','فقط موضوع‌ها','زمینهٔ کسب‌وکار، بدون شرط امتیاز تجاری','موضوع و کسب‌وکار، هر دو الزامی','نحوهٔ اجرا','آزمایشی؛ بدون تغییر انتشار','فعال در تحلیل و انتشار','آستانهٔ ارتباط تجاری','بخش‌های مجاز برای تحلیل','اجازهٔ ارسال اطلاعات انتخاب‌شده به سرویس AI را می‌دهم','اجازهٔ استفاده از حقایق کسب‌وکار در گزارش عمومی را می‌دهم','پیش‌نمایش روی خبرهای اخیر','تأیید و ذخیره','بستن','در حال بررسی…','پیش‌نمایش آماده شد','نمونهٔ خبر موجود نیست؛ فقط حالت آزمایشی قابل ذخیره است.','موضوع فعال وجود ندارد؛ فقط حالت آزمایشی قابل ذخیره است.','سرویس AI یا بودجه در دسترس نیست؛ انتشار جدید فعال نمی‌شود.','خطا در بررسی. اطلاعات و دسترسی کسب‌وکار را بررسی کنید.','خبر','امتیاز موضوع','امتیاز تجاری','نتیجهٔ پیشنهادی','اطلاعات تأییدشدهٔ قابل استفاده','نسخهٔ تأییدشده / آخرین نسخه','ذخیره شد','این تغییر فقط برای همین پروژه اعمال شود؟','برای تغییر انتشار واقعی، ابتدا پیش‌نمایش AI باید کامل شود.','حقایق تأییدشده','آماده','نیازمند تأیید دوباره','فقط اطلاعات تأییدشده و معتبر استفاده می‌شوند؛ متن‌های برند و دستورهای تولید محتوا وارد تحلیل ارتباط نمی‌شوند.','امتیاز موضوع و امتیاز تجاری مستقل‌اند و میانگین گرفته نمی‌شوند. در حالت دوشرطی، هر دو باید از آستانهٔ خود عبور کنند.','حالت آزمایشی امتیاز تجاری را ثبت می‌کند ولی قواعد انتشار فعلی را تغییر نمی‌دهد.','اطلاعات کسب‌وکار به‌طور پیش‌فرض وارد متن عمومی خبر نمی‌شوند. زبان خروجی خبرها از تنظیمات رسانه پیروی می‌کند.','پیش‌نمایش پانزده دقیقه معتبر است و با تغییر پروژه، موضوع‌ها یا اتصال باید دوباره اجرا شود.','معرفی','محصولات و خدمات','بازار هدف','رقبا','هدف‌ها','ارزش پیشنهادی','شخصیت مشتریان','پرسش‌های مشتریان','در انتظار تحلیل','نیازمند بررسی','مرتبط','نامرتبط','فعال‌سازی مجاز نیست؛ پیش‌نمایش را دوباره اجرا کنید.'],
    en: ['Business context in analysis','Linking a business alone does not change analysis or publication.','Configure and preview','Current behavior unchanged','Information source','No business','Local business','Linked Contenter business','Analysis mode','Topics only','Business context, without a business-score gate','Both topic and business required','Rollout','Shadow; publication unchanged','Live analysis and publication','Business relevance threshold','Sections allowed for analysis','I consent to sending the selected information to the AI service','Allow business facts in public reports','Preview recent news','Confirm and save','Close','Checking…','Preview completed','No sample news; only shadow mode can be saved.','No active topics; only shadow mode can be saved.','AI service or budget unavailable; live publication will not be enabled.','Check failed. Review business information and access.','News','Topic score','Business score','Proposed outcome','Approved information available for analysis','Approved / latest version','Saved','Apply this change to this project only?','A complete AI preview is required before changing live publication.','Verified facts','Ready','Approval needed again','Only approved, valid information is used; brand rules and content-generation instructions do not enter relevance analysis.','Topic and business scores are independent, never averaged. In focused mode both must pass their own threshold.','Shadow mode records business scores without changing current publication rules.','Business facts are withheld from public news by default. Output language follows media settings.','A preview is valid for fifteen minutes. Project, topic or link changes require a new preview.','Overview','Products and services','Target market','Competitors','Goals','Value proposition','Customer personas','Customer questions','Awaiting analysis','Needs review','Relevant','Unrelated','Activation unavailable; run the preview again.'],
    tr: ['Analizde işletme bağlamı','İşletme bağlantısı tek başına analizi veya yayını değiştirmez.','Yapılandır ve önizle','Mevcut davranış değişmedi','Bilgi kaynağı','İşletme yok','Yerel işletme','Bağlı Contenter işletmesi','Analiz yöntemi','Yalnızca konular','İşletme bağlamı; işletme puanı şartı yok','Hem konu hem işletme gerekli','Uygulama biçimi','Deneme; yayın değişmez','Canlı analiz ve yayın','İşletmeyle ilgililik eşiği','Analizde kullanılabilecek bölümler','Seçilen bilgilerin AI hizmetine gönderilmesine izin veriyorum','İşletme bilgilerinin herkese açık raporlarda kullanılmasına izin ver','Son haberleri önizle','Onayla ve kaydet','Kapat','Kontrol ediliyor…','Önizleme tamamlandı','Örnek haber yok; yalnızca deneme modu kaydedilebilir.','Etkin konu yok; yalnızca deneme modu kaydedilebilir.','AI hizmeti veya bütçe kullanılamıyor; canlı yayın etkinleştirilmeyecek.','Kontrol başarısız. İşletme bilgilerini ve erişimi inceleyin.','Haber','Konu puanı','İşletme puanı','Önerilen sonuç','Analizde kullanılabilecek onaylı bilgiler','Onaylı / son sürüm','Kaydedildi','Bu değişiklik yalnızca bu projeye uygulansın mı?','Canlı yayını değiştirmeden önce tam bir AI önizlemesi gerekir.','Doğrulanmış bilgiler','Hazır','Yeniden onay gerekli','Yalnızca onaylı ve geçerli bilgiler kullanılır; marka kuralları ve içerik üretim talimatları ilgililik analizine alınmaz.','Konu ve işletme puanları bağımsızdır; ortalaması alınmaz. Odaklı modda ikisi de kendi eşiğini geçmelidir.','Deneme modu işletme puanlarını kaydeder; mevcut yayın kurallarını değiştirmez.','İşletme bilgileri varsayılan olarak herkese açık haberlerden çıkarılır. Çıktı dili medya ayarlarını izler.','Önizleme on beş dakika geçerlidir. Proje, konu veya bağlantı değişirse yeniden önizleme gerekir.','Genel bakış','Ürünler ve hizmetler','Hedef pazar','Rakipler','Hedefler','Değer önerisi','Müşteri profilleri','Müşteri soruları','Analiz bekleniyor','İnceleme gerekli','İlgili','İlgisiz','Etkinleştirme yapılamıyor; önizlemeyi yeniden çalıştırın.'],
    ar: ['سياق الأعمال في التحليل','ربط النشاط التجاري وحده لا يغيّر التحليل أو النشر.','إعداد ومعاينة','السلوك الحالي لم يتغير','مصدر المعلومات','بلا نشاط تجاري','نشاط تجاري محلي','نشاط مرتبط من Contenter','وضع التحليل','المواضيع فقط','سياق الأعمال بلا شرط للدرجة التجارية','الموضوع والنشاط التجاري مطلوبان معًا','طريقة التطبيق','تجريبي؛ النشر لا يتغير','تحليل ونشر فعليان','عتبة الصلة بالنشاط التجاري','الأقسام المسموح بها للتحليل','أوافق على إرسال المعلومات المختارة إلى خدمة AI','السماح باستخدام حقائق النشاط في التقارير العامة','معاينة الأخبار الأخيرة','تأكيد وحفظ','إغلاق','جارٍ التحقق…','اكتملت المعاينة','لا توجد أخبار نموذجية؛ يمكن حفظ الوضع التجريبي فقط.','لا توجد مواضيع نشطة؛ يمكن حفظ الوضع التجريبي فقط.','خدمة AI أو الميزانية غير متاحة؛ لن يُفعّل النشر الفعلي.','فشل التحقق. راجع معلومات النشاط وصلاحية الوصول.','الخبر','درجة الموضوع','درجة النشاط التجاري','النتيجة المقترحة','معلومات معتمدة متاحة للتحليل','الإصدار المعتمد / الأحدث','تم الحفظ','تطبيق هذا التغيير على هذا المشروع فقط؟','تلزم معاينة AI مكتملة قبل تغيير النشر الفعلي.','حقائق موثّقة','جاهز','يلزم الاعتماد مجددًا','تُستخدم المعلومات المعتمدة والسارية فقط؛ لا تدخل قواعد العلامة وتعليمات إنشاء المحتوى في تحليل الصلة.','درجتا الموضوع والنشاط مستقلتان ولا يُحسب متوسطهما. في الوضع المركّز يجب أن تتجاوز كل منهما عتبتها.','يسجّل الوضع التجريبي الدرجات التجارية دون تغيير قواعد النشر الحالية.','لا تُدرج حقائق النشاط في الأخبار العامة افتراضيًا. تتبع لغة المخرجات إعدادات المصدر.','المعاينة صالحة لخمس عشرة دقيقة. تغيير المشروع أو المواضيع أو الربط يستلزم معاينة جديدة.','التعريف','المنتجات والخدمات','السوق المستهدف','المنافسون','الأهداف','القيمة المقترحة','شخصيات العملاء','أسئلة العملاء','بانتظار التحليل','بحاجة إلى مراجعة','مرتبط','غير مرتبط','التفعيل غير متاح؛ أعد تشغيل المعاينة.'],
    es: ['Contexto empresarial en el análisis','Vincular una empresa no cambia por sí solo el análisis ni la publicación.','Configurar y previsualizar','Comportamiento actual sin cambios','Fuente de información','Sin empresa','Empresa local','Empresa vinculada de Contenter','Modo de análisis','Solo temas','Contexto empresarial, sin requisito de puntuación empresarial','Se requieren tema y empresa','Aplicación','Prueba; publicación sin cambios','Análisis y publicación activos','Umbral de relevancia empresarial','Secciones permitidas para el análisis','Autorizo el envío de la información seleccionada al servicio de IA','Permitir datos de la empresa en informes públicos','Previsualizar noticias recientes','Confirmar y guardar','Cerrar','Comprobando…','Vista previa completada','No hay noticias de muestra; solo puede guardarse el modo de prueba.','No hay temas activos; solo puede guardarse el modo de prueba.','Servicio de IA o presupuesto no disponible; no se activará la publicación.','Comprobación fallida. Revisa los datos y el acceso a la empresa.','Noticia','Puntuación del tema','Puntuación empresarial','Resultado propuesto','Información aprobada disponible para el análisis','Versión aprobada / última','Guardado','¿Aplicar este cambio solo a este proyecto?','Se requiere una vista previa completa de IA antes de cambiar la publicación activa.','Datos verificados','Listo','Se requiere una nueva aprobación','Solo se usa información aprobada y vigente; las reglas de marca y las instrucciones de creación no entran en el análisis de relevancia.','Las puntuaciones del tema y la empresa son independientes y no se promedian. En modo enfocado ambas deben superar su umbral.','El modo de prueba registra puntuaciones empresariales sin cambiar las reglas de publicación.','Los datos de la empresa se excluyen de las noticias públicas por defecto. El idioma de salida sigue la configuración de medios.','La vista previa es válida durante quince minutos. Los cambios de proyecto, tema o enlace requieren una nueva vista previa.','Presentación','Productos y servicios','Mercado objetivo','Competidores','Objetivos','Propuesta de valor','Perfiles de clientes','Preguntas de clientes','Pendiente de análisis','Requiere revisión','Relevante','No relacionado','No se puede activar; vuelve a ejecutar la vista previa.'],
    it: ['Contesto aziendale nell’analisi','Il collegamento di un’azienda da solo non cambia l’analisi o la pubblicazione.','Configura e visualizza anteprima','Comportamento attuale invariato','Fonte delle informazioni','Nessuna azienda','Azienda locale','Azienda collegata da Contenter','Modalità di analisi','Solo argomenti','Contesto aziendale, senza vincolo di punteggio aziendale','Sono richiesti argomento e azienda','Applicazione','Prova; pubblicazione invariata','Analisi e pubblicazione attive','Soglia di rilevanza aziendale','Sezioni consentite per l’analisi','Acconsento all’invio delle informazioni selezionate al servizio AI','Consenti dati aziendali nei rapporti pubblici','Anteprima delle notizie recenti','Conferma e salva','Chiudi','Verifica in corso…','Anteprima completata','Nessuna notizia di esempio; si può salvare solo la modalità di prova.','Nessun argomento attivo; si può salvare solo la modalità di prova.','Servizio AI o budget non disponibile; la pubblicazione non verrà attivata.','Verifica non riuscita. Controlla i dati e l’accesso all’azienda.','Notizia','Punteggio dell’argomento','Punteggio aziendale','Esito proposto','Informazioni approvate disponibili per l’analisi','Versione approvata / ultima','Salvato','Applicare questa modifica solo a questo progetto?','Serve un’anteprima AI completa prima di modificare la pubblicazione attiva.','Dati verificati','Pronto','Serve una nuova approvazione','Si usano solo informazioni approvate e valide; regole del marchio e istruzioni di creazione non entrano nell’analisi di rilevanza.','I punteggi dell’argomento e dell’azienda sono indipendenti e non vengono mediati. Nella modalità mirata entrambi devono superare la propria soglia.','La modalità di prova registra i punteggi aziendali senza cambiare le regole di pubblicazione.','I dati aziendali sono esclusi dalle notizie pubbliche per impostazione predefinita. La lingua segue le impostazioni dei media.','L’anteprima è valida per quindici minuti. Cambi a progetto, argomenti o collegamento richiedono una nuova anteprima.','Presentazione','Prodotti e servizi','Mercato di riferimento','Concorrenti','Obiettivi','Proposta di valore','Profili dei clienti','Domande dei clienti','In attesa di analisi','Da verificare','Pertinente','Non pertinente','Attivazione non disponibile; ripeti l’anteprima.'],
    de: ['Geschäftskontext in der Analyse','Eine Geschäftsverknüpfung allein ändert weder Analyse noch Veröffentlichung.','Konfigurieren und Vorschau','Bisheriges Verhalten unverändert','Informationsquelle','Ohne Unternehmen','Lokales Unternehmen','Verknüpftes Contenter-Unternehmen','Analysemodus','Nur Themen','Geschäftskontext ohne Geschäftsschwelle','Thema und Unternehmen erforderlich','Einführung','Testmodus; Veröffentlichung unverändert','Aktive Analyse und Veröffentlichung','Schwelle für Geschäftsrelevanz','Für die Analyse erlaubte Abschnitte','Ich stimme der Übermittlung der ausgewählten Informationen an den KI-Dienst zu','Geschäftsdaten in öffentlichen Berichten erlauben','Aktuelle Nachrichten vorab prüfen','Bestätigen und speichern','Schließen','Wird geprüft…','Vorschau abgeschlossen','Keine Beispielnachrichten; nur der Testmodus kann gespeichert werden.','Keine aktiven Themen; nur der Testmodus kann gespeichert werden.','KI-Dienst oder Budget nicht verfügbar; Veröffentlichung wird nicht aktiviert.','Prüfung fehlgeschlagen. Geschäftsdaten und Zugriff prüfen.','Nachricht','Themenbewertung','Geschäftsbewertung','Vorgeschlagenes Ergebnis','Freigegebene Informationen für die Analyse','Freigegebene / neueste Version','Gespeichert','Diese Änderung nur auf dieses Projekt anwenden?','Vor einer Änderung der aktiven Veröffentlichung ist eine vollständige KI-Vorschau erforderlich.','Geprüfte Fakten','Bereit','Erneute Freigabe erforderlich','Nur freigegebene, gültige Informationen werden genutzt; Markenregeln und Anweisungen zur Inhaltserstellung gehen nicht in die Relevanzanalyse ein.','Themen- und Geschäftsbewertung sind unabhängig und werden nicht gemittelt. Im fokussierten Modus müssen beide ihre Schwelle erfüllen.','Der Testmodus erfasst Geschäftsbewertungen, ohne aktuelle Veröffentlichungsregeln zu ändern.','Geschäftsdaten werden standardmäßig nicht öffentlich ausgegeben. Die Ausgabesprache folgt den Medieneinstellungen.','Die Vorschau gilt fünfzehn Minuten. Änderungen an Projekt, Themen oder Verknüpfung erfordern eine neue Vorschau.','Überblick','Produkte und Dienstleistungen','Zielmarkt','Wettbewerber','Ziele','Wertversprechen','Kundenprofile','Kundenfragen','Analyse ausstehend','Prüfung erforderlich','Relevant','Nicht relevant','Aktivierung nicht verfügbar; Vorschau erneut ausführen.'],
    fr: ['Contexte métier dans l’analyse','Lier une entreprise ne modifie pas à lui seul l’analyse ni la publication.','Configurer et prévisualiser','Comportement actuel inchangé','Source des informations','Sans entreprise','Entreprise locale','Entreprise liée depuis Contenter','Mode d’analyse','Thèmes uniquement','Contexte métier, sans seuil de pertinence métier','Thème et entreprise requis','Application','Essai ; publication inchangée','Analyse et publication actives','Seuil de pertinence métier','Sections autorisées pour l’analyse','J’autorise l’envoi des informations sélectionnées au service d’IA','Autoriser les données de l’entreprise dans les rapports publics','Prévisualiser les actualités récentes','Confirmer et enregistrer','Fermer','Vérification…','Aperçu terminé','Aucune actualité de test ; seul le mode d’essai peut être enregistré.','Aucun thème actif ; seul le mode d’essai peut être enregistré.','Service d’IA ou budget indisponible ; la publication ne sera pas activée.','Échec de la vérification. Vérifiez les données et l’accès à l’entreprise.','Actualité','Score du thème','Score métier','Résultat proposé','Informations approuvées disponibles pour l’analyse','Version approuvée / dernière','Enregistré','Appliquer ce changement à ce projet uniquement ?','Un aperçu IA complet est requis avant de modifier la publication active.','Faits vérifiés','Prêt','Nouvelle approbation nécessaire','Seules les informations approuvées et valides sont utilisées ; les règles de marque et les instructions de création sont exclues de l’analyse de pertinence.','Les scores du thème et de l’entreprise sont indépendants, sans moyenne. En mode ciblé chacun doit dépasser son seuil.','Le mode d’essai enregistre les scores métier sans changer les règles de publication actuelles.','Les données de l’entreprise sont exclues des actualités publiques par défaut. La langue suit les paramètres des médias.','L’aperçu est valable quinze minutes. Les changements de projet, de thème ou de lien nécessitent un nouvel aperçu.','Présentation','Produits et services','Marché cible','Concurrents','Objectifs','Proposition de valeur','Profils clients','Questions clients','En attente d’analyse','À vérifier','Pertinent','Non pertinent','Activation indisponible ; relancez l’aperçu.']
  };
  const sections = ['OVERVIEW','SERVICES','TARGET_MARKET','COMPETITORS','GOALS','VALUE_PROPOSITION','PERSONAS','FAQ'];
  const S = () => window.__researchBeeState;
  const L = i => (COPY[S()?.language] || COPY.en)[i];
  const E = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const actor = () => S()?.currentUser?.id+':'+S()?.assistantId;
  const path = () => '/admin/api/assistants/'+encodeURIComponent(S().assistantId)+'/research-context';
  let data=null, loaded='', pending='', sequence=0;
  const help = i => `<span class="research-help"><button type="button" class="info-tip" data-tooltip="${E(L(i))}" aria-label="${E(L(i))}" aria-expanded="false">i</button></span>`;
  const outcome = value => L(({pending:53,borderline:54,selected:55,rejected:56})[value]??53);
  function paint() {
    const root=document.getElementById('view-businesses'); if(!root)return;
    let card=document.getElementById('researchContextCard');
    if(!card){card=document.createElement('section');card.id='researchContextCard';card.className='card section-card contenter-card';card.dataset.dynamicCopy='';root.appendChild(card);}
    const value=loaded===actor()?data:null, active=value?.active;
    card.dataset.loadedAssistant=value?S().assistantId:'';
    card.innerHTML=`<div class="section-title"><h3>${E(L(0))} ${help(41)}</h3><span class="status">${E(active?L(active.state==='ready'?38:39):L(3))}</span></div><p class="muted">${E(L(1))}</p>${active?`<dl class="contenter-meta"><div><dt>${E(L(8))}</dt><dd>${E(L(({topics:9,contextual:10,focused:11})[active.mode]))}</dd></div><div><dt>${E(L(12))}</dt><dd>${E(L(active.rollout==='shadow'?13:14))}</dd></div><div><dt>${E(L(33))}</dt><dd>${E(active.snapshot_version??'—')} / ${E(active.latest_version??'—')}</dd></div></dl>`:''}${value?.can_write?`<div class="card-actions"><button type="button" class="btn primary" id="researchConfigure">${E(L(2))}</button></div>`:''}`;
    if(value?.shadow_pending){const note=document.createElement('p');note.className='notice';note.textContent=L(42);card.appendChild(note);}
    document.getElementById('researchConfigure')?.addEventListener('click',configure);
  }
  async function load(force=false) {
    const dialog=document.querySelector('[data-research-actor]');if(dialog&&dialog.dataset.researchActor!==actor())window.closeModal();
    if(!S()?.currentUser||!S()?.assistantId){data=null;loaded='';paint();return;}
    if(document.querySelector('.view.active')?.id!=='view-businesses')return;
    const current=actor();if(pending===current||(!force&&loaded===current)){paint();return;}
    const n=++sequence;pending=current;paint();
    try{const result=await window.req(path(),{coalesceGet:false});if(n===sequence&&current===actor()){data=result;loaded=current;}}
    catch(_){if(n===sequence&&current===actor()){data=null;loaded=current;window.toast(L(27),true);}}
    finally{if(n===sequence){pending='';paint();}}
  }
  function configure() {
    if(!data?.can_write||loaded!==actor())return;
    const current=actor(),endpoint=path(),active=data.active,brief=active?.brief;
    window.modal(E(L(0)),`<form class="research-context-form" data-dynamic-copy><div class="form-grid">
      <label class="field">${E(L(4))} ${help(40)}<select id="researchSource"><option value="none">${E(L(5))}</option><option value="local" ${!data.local_businesses.length?'disabled':''}>${E(L(6))}</option><option value="contenter" ${!data.contenter_available?'disabled':''}>${E(L(7))}</option></select></label>
      <label class="field" id="researchLocalField">${E(L(6))}<select id="researchLocal">${data.local_businesses.map(x=>`<option value="${E(x.id)}">${E(x.name)}</option>`).join('')}</select></label>
      <label class="field">${E(L(8))} ${help(41)}<select id="researchMode"><option value="topics">${E(L(9))}</option><option value="contextual">${E(L(10))}</option><option value="focused">${E(L(11))}</option></select></label>
      <label class="field">${E(L(12))} ${help(42)}<select id="researchRollout"><option value="shadow">${E(L(13))}</option><option value="live">${E(L(14))}</option></select></label>
      <label class="field" id="researchThresholdField">${E(L(15))} ${help(41)}<input type="number" id="researchThreshold" min="0" max="1" step="0.05" value="${E(active?.business_threshold??.5)}"></label>
      <fieldset class="field full" id="researchSections"><legend>${E(L(16))} ${help(40)}</legend><div class="research-checks">${sections.map((key,i)=>`<label><input type="checkbox" value="${key}" ${(brief?.selected_sections||sections.slice(0,5)).includes(key)?'checked':''}>${E(L(45+i))}</label>`).join('')}</div></fieldset>
      <fieldset class="field full" id="researchFacts"><legend>${E(L(37))}</legend><div class="research-checks">${data.facts.filter(x=>x.verified===true&&x.isActive===true).map(x=>`<label><input type="checkbox" value="${E(x.id)}" ${!brief?.selected_fact_ids||brief.selected_fact_ids.includes(x.id)?'checked':''}><span dir="auto" data-user-content="true">${E(x.label)}</span></label>`).join('')}</div></fieldset>
      <label class="research-consent full" id="researchConsentField"><input type="checkbox" id="researchConsent">${E(L(17))} ${help(40)}</label>
      <label class="research-consent full" id="researchPublicField"><input type="checkbox" id="researchPublic" ${brief?.public_business_facts?'checked':''}>${E(L(18))} ${help(43)}</label>
    </div><p class="muted">${E(L(44))}</p><div class="card-actions"><button type="button" class="btn primary" id="researchPreview">${E(L(19))}</button></div><div id="researchResult" aria-live="polite"></div><div class="card-actions"><button type="button" class="btn primary" id="researchActivate" disabled>${E(L(20))}</button></div></form>`,window.closeModal,L(21));
    const dialog=document.querySelector('#modalRoot [role=dialog]');dialog.dataset.researchActor=current;
    dialog.querySelector('#modalSubmit')?.classList.remove('primary');dialog.querySelector('.modal-foot .btn:not(#modalSubmit)')?.remove();
    const form=dialog.querySelector('form'), q=id=>form.querySelector('#'+id), activeSource=active?.source||'none';
    q('researchSource').value=activeSource;q('researchMode').value=active?.mode||'topics';if(active?.local_business_id)q('researchLocal').value=active.local_business_id;
    let preview=null,busy=false;
    function conditions(){const none=q('researchSource').value==='none';q('researchLocalField').hidden=q('researchSource').value!=='local';
      if(none)q('researchMode').value='topics';q('researchMode').disabled=busy||none;
      q('researchThresholdField').hidden=q('researchMode').value!=='focused';
      for(const id of ['researchSections','researchConsentField','researchPublicField'])q(id).hidden=none;
      q('researchFacts').hidden=q('researchSource').value!=='contenter'||!data.facts.length;
    }
    function invalidate(){preview=null;q('researchActivate').disabled=true;q('researchResult').replaceChildren();conditions();}
    form.addEventListener('submit',event=>event.preventDefault());form.addEventListener('change',invalidate);form.addEventListener('input',invalidate);conditions();
    function valid(){return current===actor()&&form.isConnected;}
    function lock(value){busy=value;form.querySelectorAll('input,select,button').forEach(x=>x.disabled=value);conditions();q('researchActivate').disabled=value||!preview||(q('researchRollout').value==='live'&&!preview.result.live_ready);}
    q('researchPreview').addEventListener('click',async()=>{
      if(busy||!form.reportValidity())return;lock(true);q('researchResult').textContent=L(22);
      const source=q('researchSource').value,params={source,mode:q('researchMode').value,rollout:q('researchRollout').value,
        local_business_id:source==='local'?Number(q('researchLocal').value):null,
        sections:Array.from(q('researchSections').querySelectorAll('input:checked'),x=>x.value),
        fact_ids:source==='contenter'?Array.from(q('researchFacts').querySelectorAll('input:checked'),x=>x.value):null,
        business_threshold:Number(q('researchThreshold').value),consent_ai:q('researchConsent').checked,public_business_facts:q('researchPublic').checked,sample_limit:5};
      try{const result=await window.req(endpoint+'/preview',{method:'POST',body:JSON.stringify(params)});if(!valid())return;preview=result;
        const text=L(({evaluated:23,no_samples:24,no_topics:25,provider_unavailable:26,budget_deferred:26,provider_failed:26})[result.result.state]??27);
        q('researchResult').innerHTML=`<p class="notice" role="status">${E(text)}</p>${result.result.rows.length?`<div class="research-table"><table><thead><tr>${[28,29,30,31].map(i=>`<th>${E(L(i))}</th>`).join('')}</tr></thead><tbody>${result.result.rows.map(row=>`<tr><td data-user-content="true" dir="auto">${E(row.title)}</td><td>${E(row.before.relevance_score??'—')} → ${E(row.after.relevance_score??'—')}</td><td>${E(row.after.business_assessment?.score??'—')}</td><td>${E(outcome(row.after.relevance_state))}</td></tr>`).join('')}</tbody></table></div>`:''}<details><summary>${E(L(32))} (${E(result.proposal.brief.claims.length)})</summary>${result.proposal.brief.claims.map(x=>`<p class="contenter-prose" data-user-content="true" dir="auto">${E(x.text)}</p>`).join('')}</details><p class="muted">${E(L(36))}</p>`;
      }catch(_){if(valid()){preview=null;q('researchResult').textContent=L(27);}}finally{if(valid())lock(false);}
    });
    q('researchActivate').addEventListener('click',async()=>{
      if(!preview||busy||!confirm(L(35)))return;lock(true);
      try{const result=await window.req(endpoint+'/activate',{method:'POST',body:JSON.stringify({preview_id:preview.preview_id,confirmed:true})});if(valid()){data=result;loaded=current;window.closeModal();paint();window.toast(L(34));}}
      catch(_){if(valid()){preview=null;q('researchResult').textContent=L(57);}}finally{if(valid())lock(false);}
    });
  }
  for(const [name,force] of [['setView',false],['setLanguage',false],['loadAll',true],['refreshBusinessUi',true]]){
    const previous=window[name];if(typeof previous!=='function')continue;
    window[name]=function(){if(name==='setLanguage'&&document.querySelector('[data-research-actor]'))window.closeModal();const result=previous.apply(this,arguments);if(result?.then)result.then(()=>load(force),()=>load(force));else load(force);return result;};
  }
  // A linked/synchronized snapshot refreshes the independent approval card; never auto-activate.
  document.addEventListener('contenter-link-updated',()=>load(true));
  const priorDetails=window.relevanceDetails;
  if(typeof priorDetails==='function')window.relevanceDetails=function(news){const html=priorDetails(news),b=news.business_assessment;if(!b)return html;return html+`<div class="notice" data-dynamic-copy><b>${E(L(30))}: ${E(b.score??'—')}</b><p data-user-content="true" dir="auto">${E(b.reason)}</p>${(b.article_evidence||[]).map(q=>`<blockquote dir="auto" data-user-content="true">${E(q)}</blockquote>`).join('')}<small>${E(L(news.business_shadow?13:14))}</small></div>`;};
  paint();load();
})();
