
    // Keep the icon span inside the logout button when switching language.
    const preserveLogoutLabel=()=>{const button=document.getElementById('logoutBtn');const label=button?.querySelector('.btn-label');if(button&&label)label.textContent=state.language==='en'?'Sign out':'خروج'};
    const previousSetLanguage=setLanguage;setLanguage=function(lang){previousSetLanguage(lang);preserveLogoutLabel()};
    preserveLogoutLabel();
    const toggleSidebarShell=()=>{const shell=document.getElementById('app'),sidebar=document.getElementById('sidebar');if(!shell||!sidebar)return;const mobile=window.matchMedia('(max-width:780px)').matches;if(mobile){toggleSidebar();return}const collapsed=shell.classList.toggle('sidebar-collapsed');document.getElementById('mobileToggle')?.setAttribute('aria-expanded',String(!collapsed))};
    const menuButton=document.getElementById('mobileToggle');if(menuButton)menuButton.onclick=event=>{event.preventDefault();event.stopPropagation();toggleSidebarShell()};
    const renderAssistantsWithDeleted=renderAssistants;renderAssistants=function(){$('assistantGrid')?.parentElement?.querySelector(':scope > .deleted-assistants-section')?.remove();renderAssistantsWithDeleted();const owner=Boolean(state.currentUser?.is_owner||state.currentUser?.role==='owner'),deleted=(state.assistants||[]).filter(x=>x.deleted_at);if(!owner||!deleted.length||!$('assistantGrid'))return;const en=state.language==='en';const section=document.createElement('section');section.className='deleted-assistants-section';section.innerHTML=`<div class="section-title" data-ui-css="declaration-12"><h3>${en?'Deleted projects (30-day recovery)':'پروژه‌های حذف‌شده (بازیابی تا ۳۰ روز)'}</h3><span class="muted">${en?'Owner only':'فقط مالک'}</span></div><div class="grid assistant-grid">${deleted.map(x=>`<article class="card assistant-card"><div class="card-top"><div><h3>${esc(x.name)}</h3><div class="muted">${esc(x.slug)}</div></div><span class="status paused">${en?'Deleted':'حذف‌شده'}</span></div><p>${en?'Deleted at: ':'زمان حذف: '}${fmtDate(x.deleted_at)}</p><div class="card-actions"><button class="btn small primary" data-ui-click="restoreAssistantFromUi('${esc(x.id)}')">${en?'Restore':'بازیابی'}</button><button class="btn small danger" data-ui-click="permanentDeleteAssistantFromUi('${esc(x.id)}','${esc(x.name)}')">${en?'Delete permanently':'حذف دائمی'}</button></div></article>`).join('')}</div>`;$('assistantGrid').insertAdjacentElement('afterend',section)};
    async function restoreAssistantFromUi(id){try{await req('/admin/api/assistants/'+id+'/restore',{method:'POST'});toast(state.language==='en'?'Project restored':'پروژه بازیابی شد');await loadAll()}catch(err){toast(friendlyError(err.message),true)}}
    async function permanentDeleteAssistantFromUi(id,name){const en=state.language==='en';if(!confirm(en?`Permanently delete ${name}? This cannot be undone.`:`پروژه «${name}» برای همیشه حذف شود؟ این کار قابل بازگشت نیست.`))return;try{await req('/admin/api/assistants/'+id+'/permanent',{method:'DELETE'});toast(en?'Project permanently deleted':'پروژه برای همیشه حذف شد');await loadAll()}catch(err){toast(friendlyError(err.message),true)}}
    openNewUserModal=function(){const en=state.language==='en',projects=(state.assistants||[]).filter(x=>!x.deleted_at),projectHtml=projects.length?projects.map(x=>`<label class="field" data-ui-css="declaration-13"><input class="new-user-project" type="checkbox" value="${esc(x.id)}"><span>${esc(x.name)}</span></label>`).join(''):`<div class="empty">${en?'No authorized projects.':'پروژه مجازی وجود ندارد.'}</div>`;modal(en?'Add user':'افزودن کاربر',`<div class="form-grid"><div class="field"><label>${en?'Username':'نام کاربری'}</label><input id="uName" autocomplete="username"></div><div class="field"><label>${en?'Role':'نقش'}</label><select id="uRole"><option value="viewer">${en?'Viewer':'مشاهده‌گر'}</option><option value="analyst">${en?'Analyst':'تحلیل‌گر'}</option><option value="editor">${en?'Editor':'ویرایشگر'}</option><option value="assistant_admin">${en?'Assistant admin':'مدیر دستیار'}</option></select></div><div class="field full"><label>${en?'Password (min 12 characters)':'رمز عبور (حداقل ۱۲ کاراکتر)'}</label><input id="uPass" type="password" autocomplete="new-password"></div><div class="field full"><label>${en?'Authorized projects':'پروژه‌های مجاز'}</label>${projectHtml}</div></div>`,async()=>{try{const assistant_ids=[...document.querySelectorAll('.new-user-project:checked')].map(x=>x.value);await req('/admin/api/users',{method:'POST',body:JSON.stringify({username:$('uName').value.trim(),password:$('uPass').value,role:$('uRole').value,assistant_ids})});closeModal();toast(en?'User created with project access':'کاربر با دسترسی پروژه ساخته شد');loadUsers()}catch(err){toast(friendlyError(err.message),true)}},en?'Create user':'ساخت کاربر')};
    deleteAssistantFromUi=async function(id,name){const item=state.assistants.find(x=>x.id===id);if(!canDeleteAssistant(item)){toast(state.language==='en'?'You cannot delete this project':'برای حذف این پروژه دسترسی ندارید',true);return}const en=state.language==='en';if(!confirm(en?`Move ${name} to deleted projects? It can be restored for 30 days.`:`پروژه «${name}» به پروژه‌های حذف‌شده منتقل شود؟ تا ۳۰ روز قابل بازیابی است.`))return;try{await req('/admin/api/assistants/'+id,{method:'DELETE'});state.assistantId='';localStorage.removeItem('research_bee_workspace');toast(en?'Project moved to deleted projects':'پروژه به بخش حذف‌شده‌ها منتقل شد');await loadAll()}catch(err){toast(friendlyError(err.message),true)}};
    // MI-085: owner-only project capacity settings.  The view is created in
    // JavaScript so older cached HTML shells can upgrade without a migration.
    (function(){
      const owner=()=>Boolean(state.currentUser?.is_owner||state.currentUser?.role==='owner');
      const canUseSettings=()=>owner()||['admin','assistant_admin','editor'].includes(state.currentUser?.role);
      function ensureView(){
        const team=document.querySelector('[data-view="team"]');
        if(team&&!document.querySelector('[data-view="settings"]')){const button=document.createElement('button');button.className='nav-btn';button.dataset.view='settings';button.dataset.labelFa='تنظیمات';button.dataset.labelEn='Settings';button.innerHTML=`<span class="nav-icon" data-icon="settings" aria-hidden="true"></span><span class="nav-text">${state.language==='en'?'Settings':'تنظیمات'}</span>`;team.parentNode.insertBefore(button,team.nextSibling);button.addEventListener('click',()=>setView('settings'));applyLucideIcons()}
        if(document.getElementById('view-settings'))return;
        const section=document.createElement('section');section.id='view-settings';section.className='view';section.innerHTML=`<div class="page-head"><div><h2 id="limitsTitle">تنظیمات پروژه</h2><p id="limitsSubtitle">سقف‌های قابل تنظیم برای پروژهٔ انتخاب‌شده؛ فقط مالک می‌تواند آن‌ها را تغییر دهد.</p></div></div><div id="limitsCard" class="card section-card"><div id="limitsNotice" class="notice">این سقف‌ها جدا از سقف پردازش ۱۰۰۰ خبر روزانه اعمال می‌شوند.</div><div class="form-grid limits-grid"><div class="field"><label id="limitSourcesLabel">حداکثر رسانه</label><input id="limitMaxSources" type="number" min="1" max="100"></div><div class="field"><label id="limitTopicsLabel">حداکثر موضوع</label><input id="limitMaxTopics" type="number" min="1" max="100"></div><div class="field"><label id="limitFreshnessLabel">حداکثر پنجره تازگی (روز)</label><input id="limitMaxFreshness" type="number" min="1" max="7"></div><div class="field"><label id="limitPublishLabel">حداکثر انتشار در هر نوبت</label><input id="limitMaxItems" type="number" min="1" max="7"></div><div class="field"><label id="limitBusinessLabel">حداکثر بیزینس</label><input id="limitMaxBusinesses" type="number" min="1" max="50"></div><div class="field"><label id="limitProjectsLabel">حداکثر پروژه برای هر کاربر</label><input id="limitMaxProjects" type="number" min="1" max="100"></div></div><button id="saveLimitsBtn" class="btn primary" type="button">ذخیره سقف‌ها</button><span id="limitsMsg" class="muted" data-ui-css="declaration-14"></span></div>`;document.querySelector('.content')?.appendChild(section)
      }
      const fieldMap={max_sources:'limitMaxSources',max_topics:'limitMaxTopics',max_freshness_window_days:'limitMaxFreshness',max_items_per_run:'limitMaxItems',max_business_profiles:'limitMaxBusinesses',max_projects_per_user:'limitMaxProjects'};
      function renderCopy(){const en=state.language==='en';const copy=en?{title:'Project settings',subtitle:'Capacity limits for the selected project; only the owner can change them.',notice:'These limits are separate from the daily 1,000-item processing budget.',sources:'Maximum media',topics:'Maximum topics',freshness:'Maximum freshness window (days)',publish:'Maximum publications per slot',business:'Maximum businesses',projects:'Maximum projects per user',save:'Save limits'}:{title:'تنظیمات پروژه',subtitle:'سقف‌های قابل تنظیم برای پروژهٔ انتخاب‌شده؛ فقط مالک می‌تواند آن‌ها را تغییر دهد.',notice:'این سقف‌ها جدا از سقف پردازش ۱۰۰۰ خبر روزانه اعمال می‌شوند.',sources:'حداکثر رسانه',topics:'حداکثر موضوع',freshness:'حداکثر پنجره تازگی (روز)',publish:'حداکثر انتشار در هر نوبت',business:'حداکثر بیزینس',projects:'حداکثر پروژه برای هر کاربر',save:'ذخیره سقف‌ها'};[['limitsTitle','title'],['limitsSubtitle','subtitle'],['limitsNotice','notice'],['limitSourcesLabel','sources'],['limitTopicsLabel','topics'],['limitFreshnessLabel','freshness'],['limitPublishLabel','publish'],['limitBusinessLabel','business'],['limitProjectsLabel','projects'],['saveLimitsBtn','save']].forEach(([id,key])=>{const el=$(id);if(el)el.textContent=copy[key]})}
      async function loadLimits(){ensureView();ensureCollectionSettingsCard();renderCopy();window.__researchBeeLocalizeSettingsCopy?.();localizeCollectionSettings();const visible=owner();document.querySelector('[data-view="settings"]')?.classList.remove('hidden');document.querySelector('#view-settings .limits-grid')?.classList.toggle('hidden',!visible);document.getElementById('saveLimitsBtn')?.classList.toggle('hidden',!visible);if(!visible||!state.assistantId)return;try{const response=await req('/admin/api/assistants/'+state.assistantId+'/limits');const limits=response.limits||{};Object.entries(fieldMap).forEach(([key,id])=>{if($(id)&&limits[key]!=null)$(id).value=limits[key]});if($('limitsMsg'))$('limitsMsg').textContent='';setTimeout(()=>window.__researchBeeLocalizeSettingsNumbers?.(),0)}catch(err){if($('limitsMsg')){$('limitsMsg').textContent=friendlyError(err.message);$('limitsMsg').className='error'}}}
      function applyLimitsVisibility(){ensureView();const visible=owner();document.querySelector('[data-view="settings"]')?.classList.toggle('hidden',!canUseSettings());document.getElementById('limitsCard')?.classList.toggle('hidden',!visible);document.querySelector('#view-settings .limits-grid')?.classList.toggle('hidden',!visible);document.getElementById('saveLimitsBtn')?.classList.toggle('hidden',!visible);if(!canUseSettings()&&document.getElementById('view-settings')?.classList.contains('active'))setView('overview')}
      const priorApply=applyRoleVisibility;applyRoleVisibility=function(){priorApply();applyLimitsVisibility()};
      const priorSetView=setView;setView=function(name){if(name==='settings'&&!canUseSettings())name='overview';priorSetView(name);if(name==='settings')loadLimits()};
      const priorLoadAll=loadAll;loadAll=async function(){await priorLoadAll();if(document.getElementById('view-settings')?.classList.contains('active'))await loadLimits();applyLimitsVisibility()};
      document.addEventListener('click',event=>{if(event.target?.id!=='saveLimitsBtn')return;(async()=>{try{const body={};Object.entries(fieldMap).forEach(([key,id])=>body[key]=Number(toLatinDigits($(id)?.value||'')));if(Object.values(body).some(value=>!Number.isFinite(value))){throw Error(state.language==='en'?'Enter valid numeric limits':'مقادیر سقف‌ها باید عدد معتبر باشند')}const response=await req('/admin/api/assistants/'+state.assistantId+'/limits',{method:'PUT',body:JSON.stringify(body)});Object.entries(fieldMap).forEach(([key,id])=>{if($(id)&&response.limits?.[key]!=null)$(id).value=state.language==='en'?String(response.limits[key]):toFaDigits(response.limits[key])});window.__researchBeeLocalizeSettingsNumbers?.();if($('limitsMsg')){$('limitsMsg').textContent=state.language==='en'?'Saved':'ذخیره شد';$('limitsMsg').className='success'}toast(state.language==='en'?'Project limits saved':'سقف‌های پروژه ذخیره شد')}catch(err){if($('limitsMsg')){$('limitsMsg').textContent=friendlyError(err.message);$('limitsMsg').className='error'}toast(friendlyError(err.message),true)}})()});
      const priorLanguage=setLanguage;setLanguage=function(lang){priorLanguage(lang);ensureView();renderCopy();applyLimitsVisibility()};ensureView();renderCopy();applyLimitsVisibility();
      window.__researchBeeLoadLimits=loadLimits;
    })();
    // Numeric rendering has one owner: the renderers call displayDigits() and
    // write the value for the final locale in the same render pass.  A previous
    // implementation used a whole-document MutationObserver (and, before that,
    // a 500ms timer) to rewrite every text node.  That observer raced with
    // renderers and caused the visible Persian/Latin digit ping-pong.  Keep a
    // tiny explicit hook for legacy integrations, but never watch or rewrite the
    // document in the background.
    (function(){
      const normalizeMarkedNumbers=scope=>{
        const root=scope&&scope.nodeType===Node.TEXT_NODE?scope.parentElement:(scope||document.body);if(!root)return;
        const nodes=[];
        if(root.matches?.('[data-number]'))nodes.push(root);
        root.querySelectorAll?.('[data-number]').forEach(node=>nodes.push(node));
        nodes.forEach(node=>{
          const raw=node.dataset.number??node.textContent??'';
          const value=displayDigits(raw);
          if(node.textContent!==value)node.textContent=value;
        });
      };
      window.__researchBeeNormalizeDigits=()=>normalizeMarkedNumbers(document.body);
      const previousSetLanguage=window.setLanguage||setLanguage;
      if(typeof previousSetLanguage==='function'){
        const setLanguageWithDigits=function(lang){const result=previousSetLanguage.call(this,lang);normalizeMarkedNumbers(document.body);return result};
        window.setLanguage=setLanguageWithDigits;setLanguage=setLanguageWithDigits;
      }
      normalizeMarkedNumbers(document.body);
    })();
