
    // MI-086/087: concise media discovery cards and the project notification inbox.
    (function(){
      loadSourceSuggestions=async function(){
        if(!state.assistantId||!$('sourceSuggestionsRows'))return;
        try{
          const payload=await req('/admin/api/assistants/'+state.assistantId+'/source-suggestions'),rows=payload.suggestions||[],en=state.language==='en',owner=payload.can_approve===true;
          $('sourceSuggestionsCard').classList.toggle('hidden',!rows.length);
          $('sourceSuggestionsRows').innerHTML=rows.map(x=>{const d=x.draft||{},status=en?'Pending owner approval':'در انتظار تأیید مالک',confidence=Number(d.confidence||0);return `<div class="channel-card" data-ui-css="declaration-7"><div class="channel-card-head"><div><b>${esc(d.name||x.name||'—')}</b><span class="muted">${esc(d.summary||'')}</span></div><span class="status draft">${status}</span></div><div class="detail-list"><div class="detail-item"><span>${en?'Fit':'تناسب'}</span><b>${esc(d.fit_reason||'—')}</b></div><div class="detail-item"><span>${en?'Confidence':'اطمینان'}</span><b>${confidence?esc((confidence*100).toFixed(0)+'%'):'—'}</b></div><div class="detail-item"><span>${en?'Coverage':'پوشش'}</span><b>${esc([d.source_type,d.region,d.language].filter(Boolean).join(' · ')||'—')}</b></div><div class="detail-item"><span>${en?'Website':'آدرس وب‌سایت'}</span><b data-latin="true">${esc(d.homepage_url||'—')}</b></div></div>${owner?`<div class="card-actions" data-ui-css="declaration-7"><button class="btn small primary" data-source-suggestion-approve="${esc(x.id)}">${en?'Approve and complete':'تأیید و بررسی اتصال'}</button><button class="btn small danger" data-source-suggestion-reject="${esc(x.id)}">${en?'Reject':'رد'}</button></div>`:''}</div>`}).join('');
          document.querySelectorAll('[data-source-suggestion-approve]').forEach(b=>b.onclick=async()=>{try{b.disabled=true;await req('/admin/api/assistants/'+state.assistantId+'/source-suggestions/'+b.dataset.sourceSuggestionApprove+'/approve',{method:'POST'});toast(en?'Source verified and added':'رسانه بررسی و ثبت شد');await loadAll();await loadSourceSuggestions()}catch(err){b.disabled=false;toast(friendlyError(err.message),true)}});
          document.querySelectorAll('[data-source-suggestion-reject]').forEach(b=>b.onclick=async()=>{try{await req('/admin/api/assistants/'+state.assistantId+'/source-suggestions/'+b.dataset.sourceSuggestionReject+'/reject',{method:'POST'});toast(en?'Suggestion rejected':'پیشنهاد رد شد');loadSourceSuggestions()}catch(err){toast(friendlyError(err.message),true)}});
        }catch(err){$('sourceSuggestionsCard')?.classList.add('hidden')}
      };
      openSourceSuggestionsModal=function(){
        if(!state.assistantId){toast(state.language==='en'?'Select a project first':'ابتدا یک پروژه را انتخاب کنین',true);return}
        const en=state.language==='en';
        modal(en?'Discover specialist media':'کشف رسانه‌های تخصصی',`<div class="notice">${en?'Enter a keyword. Up to five specialist, credible public media will be suggested. Only a short summary and website are shown until the owner approves one.':'یک کلیدواژه وارد کنین. در هر نوبت حداکثر پنج رسانه تخصصی و معتبر پیشنهاد می‌شود. تا قبل از تأیید مالک فقط توضیح کوتاه و آدرس وب‌سایت نمایش داده می‌شود.'}</div><div class="form-grid"><div class="field full"><label>${en?'Keyword':'کلیدواژه'}</label><input id="suggestSourceName" placeholder="${en?'e.g. fintech':'مثلاً فین‌تک'}"></div><div class="field full"><label>${en?'Additional angle (optional)':'زاویه بررسی (اختیاری)'}</label><textarea id="suggestSourceInstruction"></textarea></div></div>`,async()=>{const keyword=$('suggestSourceName').value.trim();if(!keyword){toast(en?'Enter a keyword':'کلیدواژه را وارد کنین',true);return}try{$('modalSubmit').disabled=true;$('modalSubmit').textContent=en?'Searching…':'در حال جست‌وجو…';const result=await req('/admin/api/assistants/'+state.assistantId+'/source-suggestions',{method:'POST',body:JSON.stringify({name:keyword,instruction:$('suggestSourceInstruction').value.trim()})});closeModal();toast(en?`${result.count||0} suggestions created`:`${toFaDigits(result.count||0)} پیشنهاد ایجاد شد`);loadSourceSuggestions()}catch(err){$('modalSubmit').disabled=false;toast(friendlyError(err.message),true)}},en?'Find media':'پیشنهاد رسانه');
      };
      async function loadNotifications(){if(state.notificationsLoaded)return;try{const data=await req('/admin/api/notifications');state.notifications=data.notifications||[];state.notificationsLoaded=true;const button=$('notificationBtn');if(button){button.dataset.unread=String(data.unread||0);button.title=state.language==='en'?`Notifications (${data.unread||0})`:`اعلان‌ها (${toFaDigits(data.unread||0)})`}}catch{} }
      function openNotifications(){const en=state.language==='en',rows=state.notifications||[];modal(en?'Notifications':'صندوق پیام',rows.length?rows.map(x=>`<div class="detail-item" data-ui-css="declaration-15"><span>${esc(fmtDate(x.created_at))}</span><b data-ui-css="detail-value-wide">${esc(x.message||'—')}</b></div>`).join(''):`<div class="empty">${en?'No new notifications.':'اعلان جدیدی برای نمایش ندارین.'}</div>`,async()=>{try{await req('/admin/api/notifications/read',{method:'POST'});await loadNotifications();closeModal()}catch(err){toast(friendlyError(err.message),true)}},en?'Mark as read':'خواندم');}
      // Notifications are secondary data. Fetch them when the user opens the
      // inbox instead of blocking every page refresh on an extra endpoint.
      if($('notificationBtn'))$('notificationBtn').onclick=async()=>{await loadNotifications();openNotifications()};
      const priorLoadAll=loadAll;loadAll=async function(){return priorLoadAll()};
      const limitsButton=$('saveLimitsBtn');if(limitsButton){limitsButton.textContent=state.language==='en'?'Save':'ثبت';limitsButton.style.marginTop='12px'}
      const priorLanguage=setLanguage;setLanguage=function(lang){priorLanguage(lang);const button=$('saveLimitsBtn');if(button){button.textContent=state.language==='en'?'Save':'ثبت';button.style.marginTop='12px'}};
    })();
