
    // MI-096: keep the content template editor on its dedicated Content page
    // instead of opening a modal or placing it inside Channels.
    (function(){
      const copy={title:{fa:'سازنده قالب محتوا',en:'Content template builder'},notice:{fa:'ویرایشگر مخصوص مالک است. بلوک‌ها را جابه‌جا کنید، سقف کاراکتر، ایموجی و راهنمای تولید هر بخش را تعیین کنید، سپس پیش‌نمایش بگیرید و منتشر کنید.',en:'Owner-only editor. Drag blocks, set a character limit, emoji and generation guidance, then preview and publish.'},destination:{fa:'مقصد',en:'Destination'},feedback:{fa:'کانال فیدبک',en:'Feedback channel'},observer:{fa:'کانال مشاهده',en:'Observer channel'},preview:{fa:'پیش‌نمایش پیام تلگرام',en:'Preview Telegram message'},publish:{fa:'انتشار',en:'Publish'},close:{fa:'بستن ویرایشگر',en:'Close editor'},empty:{fa:'بلوک خالی است',en:'No blocks'},label:{fa:'برچسب',en:'Label'},emoji:{fa:'ایموجی (اختیاری)',en:'Emoji (optional)'},max:{fa:'حداکثر کاراکتر',en:'Maximum characters'},guidance:{fa:'راهنمای تولید محتوا',en:'Generation guidance'},placeholder:{fa:'در تولید این بخش به چه نکاتی توجه شود؟',en:'What should the model consider for this section?'},show:{fa:'نمایش',en:'Show'},hide:{fa:'مخفی',en:'Hide'},safe:{fa:'قالب فقط از بلوک‌های مجاز استفاده می‌کند.',en:'Templates use approved content blocks only.'}};
      const labels={title:{fa:'عنوان',en:'Title'},summary:{fa:'خلاصه',en:'Summary'},business_connection:{fa:'ارتباط با بیزینس',en:'Business relevance'},opportunity:{fa:'فرصت',en:'Opportunity'},risk:{fa:'ریسک',en:'Risk'},source:{fa:'منبع',en:'Source'},published_at:{fa:'زمان انتشار',en:'Published time'},source_url:{fa:'لینک منبع',en:'Source link'},feedback:{fa:'دکمه‌های بازخورد',en:'Feedback buttons'},footer:{fa:'پاورقی',en:'Footer'},image:{fa:'تصویر شاخص',en:'Featured image'}};
      const removeTemplatePanel=()=>$('templateBuilderPanel')?.remove();
      window.openTemplateBuilder=async function(){
        if(!state.assistantId){toast('ابتدا یک دستیار را انتخاب کنین',true);return}
        const existing=$('templateBuilderPanel');
        if(existing){existing.classList.remove('hidden');return}
        try{
          const payload=await req('/admin/api/assistants/'+state.assistantId+'/templates');
          if(!payload.can_edit){toast(state.language==='en'?'Only the owner can edit templates':'فقط مالک می‌تواند قالب را ویرایش کند',true);return}
          const en=state.language==='en',templates=payload.templates||{};let channel='feedback',blocks=JSON.parse(JSON.stringify(templates[channel]?.blocks||[]));
          const panel=document.createElement('section');panel.id='templateBuilderPanel';panel.className='card section-card template-builder-panel';panel.innerHTML=`<div class="section-title"><div><h3>${copy.title[en?'en':'fa']}</h3><span>${en?'Edit the message layout for each Telegram destination':'چیدمان پیام هر مقصد تلگرام را ویرایش کنید'}</span></div></div><div class="notice">${copy.notice[en?'en':'fa']}</div><div class="field"><label>${copy.destination[en?'en':'fa']}</label><select id="templateChannel"><option value="feedback">${copy.feedback[en?'en':'fa']}</option><option value="observer">${copy.observer[en?'en':'fa']}</option></select></div><div id="templateCanvas" data-ui-css="declaration-6"></div><div class="card-actions" data-ui-css="declaration-3"><button type="button" class="btn small" id="templatePreviewBtn">${copy.preview[en?'en':'fa']}</button><button type="button" class="btn small primary" id="templatePublishBtn">${copy.publish[en?'en':'fa']}</button></div><div id="templatePreview" class="article-body hidden" data-ui-css="declaration-6"></div><div class="notice" data-ui-css="declaration-18">${copy.safe[en?'en':'fa']}</div>`;
          // The template editor belongs to the dedicated Content page.  Keep
          // the direct mount here as a hard boundary so it cannot briefly
          // appear on Channels while the page wrapper is still settling.
          const mount=document.getElementById('templateContentMount'),layout=document.querySelector('#view-schedule .schedule-layout'),channelsCard=document.getElementById('channelSettingsCard');if(mount)mount.replaceChildren(panel);else if(channelsCard?.parentElement===layout)channelsCard.after(panel);else layout?.append(panel);if(!panel.isConnected)return;
          const sync=()=>{panel.querySelectorAll('[data-template-index]').forEach(el=>{const i=Number(el.dataset.templateIndex),b=blocks[i];if(!b)return;b.label=el.querySelector('[data-template-label]')?.value.trim()||b.label;b.emoji=el.querySelector('[data-template-emoji]')?.value.trim()||'';b.max_chars=Number(el.querySelector('[data-template-max]')?.value||0);b.guidance=el.querySelector('[data-template-guidance]')?.value.trim()||''})};
          const render=()=>{const items=blocks.map((b,i)=>`<div class="channel-card" draggable="true" data-template-index="${i}" data-ui-css="declaration-8"><div class="channel-card-head"><div><b>${esc(labels[b.type]?.[en?'en':'fa']||b.label||b.type)}</b><span class="muted">${esc(b.type)}</span></div><button type="button" class="btn small" data-template-toggle="${i}">${b.visible===false?copy.show[en?'en':'fa']:copy.hide[en?'en':'fa']}</button></div><div class="form-grid" data-ui-css="declaration-6"><div class="field"><label>${copy.label[en?'en':'fa']}</label><input data-template-label value="${esc(b.label||'')}"></div><div class="field"><label>${copy.emoji[en?'en':'fa']}</label><input data-template-emoji value="${esc(b.emoji||'')}" maxlength="16"></div><div class="field"><label>${copy.max[en?'en':'fa']}</label><input data-template-max type="number" min="20" max="1200" value="${esc(b.max_chars||0)}"></div><div class="field full"><label>${copy.guidance[en?'en':'fa']}</label><textarea data-template-guidance placeholder="${copy.placeholder[en?'en':'fa']}">${esc(b.guidance||'')}</textarea></div></div></div>`).join('');$('templateCanvas').innerHTML=items||`<div class="empty">${copy.empty[en?'en':'fa']}</div>`;panel.querySelectorAll('[data-template-toggle]').forEach(button=>button.onclick=()=>{sync();const i=Number(button.dataset.templateToggle);blocks[i].visible=blocks[i].visible===false;render()});panel.querySelectorAll('[data-template-index]').forEach(el=>{el.ondragstart=e=>e.dataTransfer.setData('text/plain',el.dataset.templateIndex);el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();sync();const from=Number(e.dataTransfer.getData('text/plain')),to=Number(el.dataset.templateIndex),moved=blocks.splice(from,1)[0];blocks.splice(to,0,moved);render()}})};
          panel.querySelector('#templateChannel').onchange=()=>{sync();channel=panel.querySelector('#templateChannel').value;blocks=JSON.parse(JSON.stringify(templates[channel]?.blocks||[]));panel.querySelector('#templatePreview').classList.add('hidden');render()};panel.querySelector('#templatePreviewBtn').onclick=async()=>{try{sync();const button=panel.querySelector('#templatePreviewBtn');button.disabled=true;const result=await req('/admin/api/assistants/'+state.assistantId+'/templates/'+channel+'/preview',{method:'POST',body:JSON.stringify({blocks,publish:false})});panel.querySelector('#templatePreview').innerHTML=safePreview(result.preview);panel.querySelector('#templatePreview').classList.remove('hidden')}catch(err){toast(friendlyError(err.message),true)}finally{panel.querySelector('#templatePreviewBtn').disabled=false}};panel.querySelector('#templatePublishBtn').onclick=async()=>{try{sync();const button=panel.querySelector('#templatePublishBtn');button.disabled=true;await req('/admin/api/assistants/'+state.assistantId+'/templates/'+channel,{method:'PUT',body:JSON.stringify({blocks,publish:true})});toast(en?'Template published':'قالب منتشر شد')}catch(err){toast(friendlyError(err.message),true)}finally{panel.querySelector('#templatePublishBtn').disabled=false}};render();
        }catch(err){toast(friendlyError(err.message),true)}
      };
      const canEdit=()=>Boolean(state.currentUser?.is_owner||state.currentUser?.role==='owner');
      const removeTemplateButton=()=>document.querySelectorAll('#templateBuilderBtn').forEach(button=>button.remove());
      const oldEnsureWorkspaceActions=ensureWorkspaceActions;ensureWorkspaceActions=function(){oldEnsureWorkspaceActions();removeTemplateButton()};
      // Do not fetch and build the template editor during every dashboard
      // refresh.  It is a Content-page editor, so hydrate it only when that
      // page is active; this removes an avoidable API request and a large DOM
      // insertion from the critical first paint.
      const queueTemplatePanel=()=>{removeTemplateButton();const active=document.getElementById('view-template-content')?.classList.contains('active');if(canEdit()&&active&&state.assistantId&&!$('templateBuilderPanel'))window.openTemplateBuilder()};
      const oldLoadAll=loadAll;loadAll=async function(){const active=document.getElementById('view-template-content')?.classList.contains('active');if(!active)removeTemplatePanel();const result=await oldLoadAll();queueTemplatePanel();return result};
      const oldLanguage=setLanguage;setLanguage=function(lang){oldLanguage(lang);removeTemplatePanel();queueTemplatePanel()};
      // The template button is removed by the explicit workspace/render hooks
      // above.  Keep this observer scoped to the small modal root for legacy
      // cached shells; observing the whole document made every table repaint
      // run this no-op cleanup.
      new MutationObserver(removeTemplateButton).observe(document.getElementById('modalRoot')||document.body,{subtree:true,childList:true});
      removeTemplateButton();setTimeout(queueTemplatePanel,0);
    })();
