
    // MI-098: review-first market insights. The panel is additive: if the
    // optional endpoint is unavailable, the existing news queue still works.
    (function(){
      const baseLoadAll=loadAll;
      const panel=()=>document.getElementById('insightsPanel');
      const renderInsights=()=>{const root=document.getElementById('insightsSummary'),trends=document.getElementById('insightsTrends'),articles=document.getElementById('insightsArticleRows'),data=state.insights;if(!root||!trends)return;const en=state.language==='en';const title=document.querySelector('[data-insights-title]'),subtitle=document.querySelector('[data-insights-subtitle]');if(title)title.textContent=en?'Quality and trends':'کیفیت و روند';if(subtitle)subtitle.textContent=en?'Priority, quality, source conflicts and topic trends':'اولویت، کیفیت، تعارض روایت‌ها و روند موضوعات';if(!data){root.innerHTML='<div class="empty">'+(en?'No insight data yet.':'هنوز دادهٔ تحلیلی دریافت نشده است.')+'</div>';if(articles)articles.innerHTML='';trends.innerHTML='';return}const health=data.source_health||{},num=v=>en?String(Number(v||0)):toFaDigits(Number(v||0));root.innerHTML=[['urgent_count',en?'Urgent alerts':'هشدار فوری'],['review_conflicts',en?'Source conflicts to review':'تعارض‌های نیازمند بررسی'],['degraded',en?'Degraded media':'رسانهٔ degraded']].map(([key,label])=>`<div class="card kpi"><div class="kpi-label">${label}</div><div class="kpi-value">${num(key==='degraded'?health[key]:data[key])}</div></div>`).join('');if(articles){const items=(data.articles||[]).slice(0,12);articles.innerHTML=items.length?items.map(item=>{const quality=Number(item.quality?.score||0),priority=item.priority==='urgent'?(en?'Urgent':'فوری'):(en?'Digest':'عادی'),conflict=item.conflict?.state==='review'?(en?'Review':'بررسی'):(en?'Aligned':'هم‌راستا'),translation=item.translation_available?(en?'Available':'قابل ترجمه'):(en?'Native':'اصلی');return `<tr><td><b>${esc((item.title||'—').slice(0,100))}</b><div class="muted">${esc(item.source||'—')}</div></td><td>${priority}</td><td>${en?quality.toFixed(2):toFaDigits(quality.toFixed(2))}</td><td>${conflict}</td><td>${translation}</td></tr>`}).join(''):`<tr><td colspan="5" class="empty">${en?'No analyzed news in this period.':'در این بازه خبر تحلیلی ثبت نشده است.'}</td></tr>`}const rows=(data.trends||[]).slice(0,6);trends.innerHTML=rows.length?rows.map(item=>{const arrow=item.direction==='up'?'↑':item.direction==='down'?'↓':'→';return `<div class="detail-item"><div><b>${esc(item.topic||'—')}</b><div class="muted">${en?'Current':'فعلی'}: ${num(item.current)} · ${en?'Previous':'قبلی'}: ${num(item.previous)}</div></div><span class="chip">${arrow} ${num(Math.abs(item.delta))}</span></div>`}).join(''):`<div class="empty">${en?'No trend data for this period.':'برای این بازه روندی ثبت نشده است.'}</div>`};
      const renderInsightExtras=()=>{const root=document.getElementById('insightsSources'),data=state.insights;if(!root||!data)return;const en=state.language==='en',sources=data.source_health?.sources||[];root.innerHTML=sources.length?sources.map(source=>`<div class="detail-item"><div><b>${esc(source.name||source.source_key||'—')}</b><div class="muted">${esc(source.last_error||'—')}</div></div>${source.fallback_candidate?`<button type="button" class="btn small" data-source-fallback="${esc(source.id)}">${en?'Use official fallback':'استفاده از fallback رسمی'}</button>`:''}</div>`).join(''):`<div class="muted">${en?'No degraded media.':'رسانهٔ degraded وجود ندارد.'}</div>`;document.querySelectorAll('#insightsArticleRows tr').forEach(row=>{const item=(data.articles||[])[row.rowIndex-1];if(!item||!item.translation_available)return;const cell=row.lastElementChild;if(cell&&!cell.querySelector('[data-insight-translate]'))cell.innerHTML=`<button type="button" class="btn small" data-insight-translate="${esc(item.analysis_id)}">${en?'Translate':'ترجمه'}</button>`})};
      async function refreshInsights(){if(!state.assistantId){state.insights=null;renderInsights();renderInsightExtras();return}const button=document.getElementById('refreshInsightsBtn');if(button)button.disabled=true;try{state.insights=await req('/insights?assistant_id='+encodeURIComponent(state.assistantId)+'&days=7');renderInsights();renderInsightExtras()}catch(err){state.insights=null;renderInsights();renderInsightExtras();toast(state.language==='en'?'Insights could not be loaded':'داده‌های تحلیلی بارگذاری نشد',true)}finally{if(button)button.disabled=false}}
      loadAll=async function(){const result=await baseLoadAll();if(panel()?.closest('.view.active'))await refreshInsights();return result};
      window.__researchBeeRefreshInsights=refreshInsights;
      document.addEventListener('click',async event=>{if(event.target?.id==='refreshInsightsBtn')return refreshInsights();const translate=event.target?.closest?.('[data-insight-translate]');if(translate){try{translate.disabled=true;const result=await req('/insights/translate?assistant_id='+encodeURIComponent(state.assistantId),{method:'POST',body:JSON.stringify({analysis_id:translate.dataset.insightTranslate,target_language:state.language==='en'?'en':'fa'})});$('runResult').textContent=JSON.stringify(result.translation||result,null,2);toast(state.language==='en'?'Translation ready for review':'ترجمه برای بررسی آماده شد')}catch(err){toast(friendlyError(err.message),true)}finally{translate.disabled=false}}const fallback=event.target?.closest?.('[data-source-fallback]');if(fallback){try{fallback.disabled=true;await req('/admin/api/sources/'+encodeURIComponent(fallback.dataset.sourceFallback)+'/official-fallback?assistant_id='+encodeURIComponent(state.assistantId),{method:'POST'});toast(state.language==='en'?'Official fallback selected; health probe pending':'fallback رسمی انتخاب شد؛ بررسی سلامت در انتظار است');await refreshInsights()}catch(err){toast(friendlyError(err.message),true)}finally{fallback.disabled=false}}});
      const baseSetLanguage=setLanguage;setLanguage=function(lang){baseSetLanguage(lang);renderInsights();renderInsightExtras()};
      // Do not observe this panel's subtree: renderInsightExtras() updates
      // #insightsSources itself, so observing childList here created a
      // self-triggering MutationObserver loop that eventually froze clicks.
      renderInsights();renderInsightExtras();
    })();
