
    // I-059/I-060/I-064/I-066 — bounded MVPs: command palette, personal
    // saved views, actionable incident inbox, and safe non-publishing bulk
    // actions.  All controls use the existing RBAC-scoped API and shell.
    (function(){
      const selected=new Set();state.newsViews=[];state.incidents=[];state.lastBulk=null;
      const en=()=>state.language==='en';
      // All eight locales share the same catalog resolver.  The old helper
      // treated every non-English language as Persian, which was the source
      // of the mixed Turkish/Arabic/etc. screens seen in production.
      const label=(fa,english)=>window.__miLabel?window.__miLabel(fa,english):(en()?english:fa);
      function ensureNewsTools(){
        const bar=document.querySelector('#view-content .filter-bar');if(!bar||document.getElementById('newsViewSelect'))return;
        const wrap=document.createElement('span');wrap.className='news-list-tools';wrap.innerHTML='<select id="newsViewSelect" aria-label="Saved view"></select><button class="btn small" id="saveNewsViewBtn" type="button"></button><button class="btn small" id="deleteNewsViewBtn" type="button"></button>';
        bar.appendChild(wrap);
        const bulk=document.createElement('div');bulk.id='bulkNewsBar';bulk.className='bulk-news-bar';bulk.innerHTML='<span class="muted" id="bulkNewsCount"></span><button class="btn small" id="bulkArchiveBtn" type="button"></button><button class="btn small" id="bulkRejectBtn" type="button"></button><button class="btn small" id="bulkLabelBtn" type="button"></button><button class="btn small" id="bulkUndoBtn" type="button" hidden></button><span class="muted">'+label('انتشار گروهی عمداً غیرفعال است','Bulk publishing is disabled by safety gate')+'</span>';bar.parentNode.insertBefore(bulk,bar.nextSibling);
        document.getElementById('saveNewsViewBtn').onclick=openSaveView;
        document.getElementById('newsViewSelect').onchange=()=>{const view=state.newsViews.find(item=>item.id===document.getElementById('newsViewSelect').value);if(view)applyView(view);renderNewsTools()};
        document.getElementById('deleteNewsViewBtn').onclick=deleteSelectedView;
        document.getElementById('bulkArchiveBtn').onclick=()=>runBulk('archive');document.getElementById('bulkRejectBtn').onclick=()=>runBulk('reject');document.getElementById('bulkLabelBtn').onclick=()=>runBulk('label');document.getElementById('bulkUndoBtn').onclick=undoBulk;
        renderNewsTools();
      }
      function renderNewsTools(){
        const select=document.getElementById('newsViewSelect'),save=document.getElementById('saveNewsViewBtn'),remove=document.getElementById('deleteNewsViewBtn');if(!select)return;
        select.innerHTML='<option value="">'+label('نمای فعلی','Current view')+'</option>'+state.newsViews.map(view=>`<option value="${esc(view.id)}">${esc(view.name)}${view.is_default?' · '+label('پیش‌فرض','default'):''}</option>`).join('');
        if(save)save.textContent=label('ذخیره نما','Save view');if(remove){remove.textContent=label('حذف نما','Delete view');remove.disabled=!select.value}
        const bulk=document.getElementById('bulkNewsBar'),count=document.getElementById('bulkNewsCount');if(bulk){bulk.classList.toggle('active',selected.size>0);if(count)count.textContent=label(`${toFaDigits(selected.size)} خبر انتخاب شده`,` ${selected.size} selected`);['bulkArchiveBtn','bulkRejectBtn','bulkLabelBtn'].forEach((id,i)=>{const el=document.getElementById(id);if(el)el.textContent=[label('بایگانی','Archive'),label('رد','Reject'),label('برچسب','Label')][i]});const undo=document.getElementById('bulkUndoBtn');const validUndo=state.lastBulk&&Date.now()-state.lastBulk.at<10*60*1000;if(undo){undo.hidden=!validUndo;undo.textContent=label('بازگردانی','Undo')}}
      }
      async function loadNewsViews(){ensureNewsTools();if(!state.assistantId)return;const key=String(state.assistantId);if(state.newsViewsLoadedFor===key)return;try{const data=await req('/admin/api/assistants/'+key+'/news-views');state.newsViews=data.views||[];state.newsViewsLoadedFor=key;renderNewsTools()}catch(err){state.newsViews=[];renderNewsTools()}}
      function currentFilters(){return {status:document.getElementById('publicationStatus')?.value||'',query:document.getElementById('publicationSearch')?.value||''}}
      function applyView(view){const filters=view.filters||{};if(document.getElementById('publicationStatus'))document.getElementById('publicationStatus').value=filters.status||'';if(document.getElementById('publicationSearch'))document.getElementById('publicationSearch').value=filters.query||'';state.publicationPage=1;renderPublications();toast(label('نما اعمال شد','View applied'))}
      function openSaveView(){const body='<div class="field"><label>'+label('نام نما','View name')+'</label><input id="newsViewName" maxlength="80" placeholder="'+label('مثلاً خبرهای نیازمند بررسی','e.g. Needs review')+'"></div><label class="field" data-ui-css="declaration-13"><input id="newsViewDefault" type="checkbox">'+label('این نما پیش‌فرض باشد','Make this the default view')+'</label>';modal(label('ذخیره نمای خبرها','Save News List view'),body,async()=>{const name=document.getElementById('newsViewName')?.value.trim();if(!name){toast(label('نام نما را وارد کنین','Enter a view name'),true);return}try{const data=await req('/admin/api/assistants/'+state.assistantId+'/news-views',{method:'POST',body:JSON.stringify({name,filters:currentFilters(),is_default:Boolean(document.getElementById('newsViewDefault')?.checked)})});state.newsViews=data.views||[];closeModal();renderNewsTools();toast(label('نما ذخیره شد','View saved'))}catch(err){toast(friendlyError(err.message),true)}},label('ذخیره','Save'))}
      async function deleteSelectedView(){const select=document.getElementById('newsViewSelect'),viewId=select?.value;if(!viewId)return;if(!window.confirm(label('این نمای ذخیره‌شده حذف شود؟','Delete this saved view?')))return;try{const data=await req('/admin/api/assistants/'+state.assistantId+'/news-views/'+viewId,{method:'DELETE'});state.newsViews=data.views||[];if(select)select.value='';renderNewsTools();toast(label('نما حذف شد','View deleted'))}catch(err){toast(friendlyError(err.message),true)}}
      window.togglePublicationSelection=id=>{if(selected.has(id))selected.delete(id);else selected.add(id);renderNewsTools()};
      async function runBulk(action){const ids=[...selected];if(!ids.length)return;let labelValue=null;if(action==='label')labelValue=window.prompt(label('برچسب کوتاه را وارد کنین','Enter a short label'));if(action==='label'&&!labelValue)return;const message=action==='archive'?label('خبرهای انتخاب‌شده بایگانی شوند؟','Archive selected news?'):action==='reject'?label('خبرهای انتخاب‌شده رد شوند؟','Reject selected news?'):label('برچسب روی خبرهای انتخاب‌شده ثبت شود؟','Apply this label to selected news?');if(!window.confirm(message))return;try{await req('/admin/api/assistants/'+state.assistantId+'/publications/bulk',{method:'POST',body:JSON.stringify({ids,action,label:labelValue})});state.lastBulk={ids,at:Date.now()};selected.clear();renderNewsTools();toast(label('عملیات گروهی انجام شد؛ تا ۱۰ دقیقه امکان بازگردانی دارید.','Bulk action completed; undo is available for 10 minutes.'));await loadAll()}catch(err){toast(friendlyError(err.message),true)}}
      async function undoBulk(){const last=state.lastBulk;if(!last)return;if(Date.now()-last.at>=10*60*1000){state.lastBulk=null;renderNewsTools();toast(label('مهلت بازگردانی تمام شده است.','Undo window has expired.'),true);return}if(!window.confirm(label('آخرین عملیات گروهی بازگردانی شود؟','Undo the last bulk action?')))return;try{await req('/admin/api/assistants/'+state.assistantId+'/publications/bulk/undo',{method:'POST',body:JSON.stringify({ids:last.ids})});state.lastBulk=null;selected.clear();toast(label('عملیات گروهی بازگردانی شد.','Bulk action undone'));await loadAll()}catch(err){toast(friendlyError(err.message),true)}}
      const baseRenderPublications=renderPublications;renderPublications=function(){baseRenderPublications();ensureNewsTools();const header=document.querySelector('#view-content thead tr');if(header&&!header.querySelector('[data-publication-select-all]')){const th=document.createElement('th');th.dataset.publicationSelectAll='true';th.innerHTML='<input type="checkbox" class="publication-select" aria-label="'+label('انتخاب همه','Select all')+'">';header.insertBefore(th,header.firstChild);th.querySelector('input').onchange=event=>{document.querySelectorAll('#publicationRows [data-publication-id]').forEach(input=>{if(event.target.checked)selected.add(input.dataset.publicationId);else selected.delete(input.dataset.publicationId);input.checked=event.target.checked});renderNewsTools()}}const rows=document.querySelectorAll('#publicationRows tr');rows.forEach(row=>{if(row.dataset.bulkReady==='true')return;const title=row.querySelector('button[onclick*="openPublication"]');const match=title?.getAttribute('onclick')?.match(/openPublication\('([^']+)'\)/);if(!match)return;row.dataset.bulkReady='true';row.dataset.publicationId=match[1];const cell=document.createElement('td');cell.innerHTML=`<input type="checkbox" class="publication-select" data-publication-id="${esc(match[1])}" ${selected.has(match[1])?'checked':''} aria-label="${label('انتخاب خبر','Select news')}">`;cell.querySelector('input').onchange=()=>window.togglePublicationSelection(match[1]);row.insertBefore(cell,row.firstChild)});renderNewsTools()};
      const freshnessCopy={
        fa:{title:'تأخیر در خزش و تحلیل',detail:'برای این دستیار منبع فعال وجود دارد، اما اجرای موفق اخیر ثبت نشده یا بیش از ۳۶ ساعت از آن گذشته است.',last:'آخرین اجرای موفق',none:'اجرای موفقی ثبت نشده',action:'بررسی زمان‌بندی',severity:{critical:'بحرانی',warning:'هشدار'},sources:'منابع فعال'},
        en:{title:'Collection and analysis are delayed',detail:'This assistant has enabled sources, but no successful run is recorded or the last run was more than 36 hours ago.',last:'Last successful run',none:'No successful run recorded',action:'Review schedule',severity:{critical:'Critical',warning:'Warning'},sources:'Enabled sources'},
        tr:{title:'Toplama ve analiz gecikiyor',detail:'Bu asistanda etkin kaynaklar var ancak başarılı bir çalışma yok veya son çalışmanın üzerinden 36 saatten fazla geçti.',last:'Son başarılı çalışma',none:'Başarılı çalışma kaydı yok',action:'Zamanlamayı incele',severity:{critical:'Kritik',warning:'Uyarı'},sources:'Etkin kaynaklar'},
        ar:{title:'تأخر الجمع والتحليل',detail:'توجد مصادر مفعّلة لهذا المساعد، لكن لا يوجد تشغيل ناجح أو مضى على آخر تشغيل أكثر من ٣٦ ساعة.',last:'آخر تشغيل ناجح',none:'لا يوجد تشغيل ناجح مسجل',action:'مراجعة الجدول',severity:{critical:'حرج',warning:'تحذير'},sources:'المصادر المفعّلة'},
        it:{title:'Raccolta e analisi in ritardo',detail:'Questo assistente ha fonti attive, ma non risulta un’esecuzione riuscita o l’ultima risale a oltre 36 ore fa.',last:'Ultima esecuzione riuscita',none:'Nessuna esecuzione riuscita registrata',action:'Rivedi la pianificazione',severity:{critical:'Critico',warning:'Avviso'},sources:'Fonti attive'},
        es:{title:'Recopilación y análisis retrasados',detail:'Este asistente tiene fuentes activas, pero no hay ejecuciones correctas o la última fue hace más de 36 horas.',last:'Última ejecución correcta',none:'No hay ejecuciones correctas registradas',action:'Revisar programación',severity:{critical:'Crítico',warning:'Aviso'},sources:'Fuentes activas'},
        de:{title:'Sammlung und Analyse sind verzögert',detail:'Für diesen Assistenten sind Quellen aktiviert, aber es gibt keinen erfolgreichen Lauf oder der letzte liegt mehr als 36 Stunden zurück.',last:'Letzter erfolgreicher Lauf',none:'Kein erfolgreicher Lauf erfasst',action:'Zeitplan prüfen',severity:{critical:'Kritisch',warning:'Warnung'},sources:'Aktive Quellen'},
        fr:{title:'Collecte et analyse en retard',detail:'Cet assistant possède des sources actives, mais aucune exécution réussie n’est enregistrée ou la dernière date de plus de 36 heures.',last:'Dernière exécution réussie',none:'Aucune exécution réussie enregistrée',action:'Vérifier le calendrier',severity:{critical:'Critique',warning:'Avertissement'},sources:'Sources actives'},
      };
      function ensureIncidentPanel(){const root=document.getElementById('view-operations');if(!root||document.getElementById('incidentInbox'))return;if(!root.querySelector('#incidentInbox')){const section=document.createElement('div');section.id='incidentInbox';section.className='card section-card';section.style.marginTop='14px';section.innerHTML='<div class="section-title"><h3>'+label('صندوق رخداد و هشدار','Incident inbox')+'</h3><button class="btn small" id="refreshIncidentsBtn" type="button">'+label('بازخوانی','Refresh')+'</button></div><div id="incidentRows" class="incident-list"><div class="empty">'+label('در حال دریافت رخدادها…','Loading incidents…')+'</div></div>';root.appendChild(section);document.getElementById('refreshIncidentsBtn').onclick=()=>loadIncidents(true)}}
      function renderIncidents(){ensureIncidentPanel();const root=document.getElementById('incidentRows');if(!root)return;const items=state.incidents||[];root.innerHTML=items.length?items.map(item=>{if(item.is_freshness_alert){const copy=freshnessCopy[state.language]||freshnessCopy.en;const last=item.last_success_at?fmtDate(item.last_success_at):copy.none;return `<div class="incident-item"><span class="incident-severity ${esc(item.severity||'warning')}">${esc(copy.severity[item.severity]||copy.severity.warning)}</span><div class="incident-copy"><b>${esc(copy.title)} · ${esc(item.assistant_name||'')}</b><small>${esc(copy.detail)}</small><small class="muted">${esc(copy.last)}: ${esc(last)} · ${esc(copy.sources)}: ${esc(item.source_count||0)}</small></div><div class="incident-actions"><button class="btn small" data-ui-click="setView('settings')">${copy.action}</button></div></div>`}const timestamp=item.created_at?fmtDate(item.created_at):'—';return `<div class="incident-item"><span class="incident-severity ${esc(item.severity||'info')}">${esc(item.severity||'info')}</span><div class="incident-copy"><b>${esc(item.message||'—')}</b><small class="muted">${esc(timestamp)}</small></div><div class="incident-actions">${item.suggested_action==='health_check'?`<button class="btn small" data-ui-click="runIncidentHealth('${esc(item.assistant_id||'')}')">${label('بررسی سلامت','Health check')}</button>`:`<button class="btn small" data-ui-click="setView('content')">${label('بررسی خبرها','Review news')}</button>`}<button class="btn small" data-ui-click="closeIncident('${esc(item.id)}')">${label('بستن','Close')}</button></div></div>`}).join(''):`<div class="empty">${label('رخداد بازی برای نمایش نیست.','No open incidents.')}</div>`}
      async function loadIncidents(force=false){ensureIncidentPanel();const key=String(state.assistantId||'');if(!force&&state.incidentsLoadedFor===key)return;try{const data=await req('/admin/api/incidents'+(key?'?assistant_id='+encodeURIComponent(key):''),force?{coalesceGet:false}:{});state.incidents=(data.incidents||[]).filter(item=>item.status==='open');state.incidentsLoadedFor=key;renderIncidents()}catch(err){state.incidentsLoadedFor=null;state.incidents=[];renderIncidents();toast(friendlyError(err.message),true)}}
      window.closeIncident=async id=>{try{await req('/admin/api/incidents/'+id+'/close',{method:'POST'});await loadIncidents(true)}catch(err){toast(friendlyError(err.message),true)}};
      window.runIncidentHealth=async id=>{try{await req('/sources/health-probe'+(id?'?assistant_id='+encodeURIComponent(id):''),{method:'POST'});toast(label('بررسی سلامت انجام شد','Health check completed'));await loadIncidents(true)}catch(err){toast(friendlyError(err.message),true)}};
      function commandPalette(){if(document.getElementById('commandPaletteBackdrop')){document.getElementById('commandPaletteBackdrop').remove();return}const backdrop=document.createElement('div');backdrop.id='commandPaletteBackdrop';backdrop.className='command-palette-backdrop';backdrop.innerHTML='<div class="command-palette" role="dialog" aria-modal="true" aria-label="Command palette"><input id="commandPaletteInput" autocomplete="off" placeholder="'+label('جست‌وجوی پروژه، صفحه یا اقدام…','Search project, page or action…')+'"><div id="commandPaletteList" class="command-palette-list"></div></div>';document.body.appendChild(backdrop);const input=document.getElementById('commandPaletteInput'),list=document.getElementById('commandPaletteList');const close=()=>backdrop.remove();backdrop.addEventListener('click',event=>{if(event.target===backdrop)close()});function items(){const actions=[...document.querySelectorAll('.nav-btn[data-view]')].filter(x=>!x.classList.contains('hidden')).map(x=>({title:x.querySelector('.nav-text')?.textContent||'',hint:label('صفحه','Page'),run:()=>{setView(x.dataset.view);close()}}));(state.assistants||[]).filter(x=>!x.deleted_at).forEach(x=>actions.push({title:x.name,hint:label('پروژه','Project'),run:()=>{state.assistantId=x.id;localStorage.setItem('research_bee_workspace',x.id);loadAll();setView('assistants');close()}}));if(state.currentUser?.is_owner||['admin','assistant_admin','editor'].includes(state.currentUser?.role))actions.push({title:label('اجرای pipeline','Run pipeline'),hint:label('اقدام','Action'),run:()=>{$('runPipelineBtn')?.click();close()}});if(state.currentUser?.is_owner)actions.push({title:label('بررسی سلامت رسانه‌ها','Check media health'),hint:label('اقدام','Action'),run:()=>{$('healthProbeBtn')?.click();close()}});return actions}function render(){const q=input.value.trim().toLocaleLowerCase();list.innerHTML=items().filter(x=>!q||x.title.toLocaleLowerCase().includes(q)).slice(0,30).map((x,i)=>`<button class="command-palette-item" data-command-index="${i}"><span>${esc(x.title)}</span><small>${esc(x.hint)}</small></button>`).join('')||'<div class="empty">'+label('نتیجه‌ای پیدا نشد.','No matching command.')+'</div>';list.querySelectorAll('[data-command-index]').forEach((button,index)=>button.onclick=()=>items().filter(x=>!q||x.title.toLocaleLowerCase().includes(q)).slice(0,30)[index].run())}input.addEventListener('input',render);input.addEventListener('keydown',event=>{if(event.key==='Escape')close();if(event.key==='Enter')list.querySelector('.command-palette-item')?.click()});render();input.focus()}
      document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();commandPalette()}if(event.key==='Escape')document.getElementById('commandPaletteBackdrop')?.remove()});
      const baseLoadAll=loadAll;loadAll=async function(){const result=await baseLoadAll();if(document.getElementById('view-content')?.classList.contains('active'))await loadNewsViews();if(document.getElementById('view-operations')?.classList.contains('active'))await loadIncidents();return result};
      const baseSetLanguage=setLanguage;setLanguage=function(language){baseSetLanguage(language);renderNewsTools();renderIncidents()};
      ensureNewsTools();ensureIncidentPanel();renderNewsTools();renderIncidents();window.loadNewsViews=loadNewsViews;window.loadIncidents=loadIncidents;window.toggleCommandPalette=commandPalette;
    })();
    /* MI-164: owner-routed support inbox. The view is created lazily so existing layouts remain stable. */
    (()=>{
      if(window.__beeCanonicalSupport)return;
      const copy=()=>{const t=(fa,en)=>localeLabel(fa,en),normal={fa:'عادی',en:'Normal',tr:'Normal',ar:'عادي',it:'Normale',es:'Normal',de:'Normal',fr:'Normale'}[state.language]||'Normal';return {title:t('پشتیبانی','Support'),intro:t('برای مالک حساب تیکت ثبت کنین؛ پاسخ و وضعیت همین‌جا مدیریت می‌شود.','Create a ticket for the account owner; replies and status are managed here.'),newTitle:t('تیکت جدید','New ticket'),subject:t('موضوع تیکت','Ticket topic'),body:t('شرح درخواست یا مشکل','Describe the request or issue'),priority:t('اولویت','Priority'),submit:t('ارسال تیکت','Send ticket'),refresh:t('بازخوانی','Refresh'),empty:t('هنوز تیکتی ثبت نشده است.','No tickets yet.'),reply:t('پاسخ مالک','Owner reply'),status:t('وضعیت','Status'),save:t('ذخیره','Save'),open:t('باز','Open'),in_progress:t('در حال پیگیری','In progress'),waiting_user:t('منتظر پاسخ کاربر','Waiting for user'),resolved:t('حل‌شده','Resolved'),closed:t('بسته‌شده','Closed'),low:t('کم','Low'),normal,high:t('زیاد','High'),urgent:t('فوری','Urgent')}};
      const ensureNav=()=>{const legacyMenu=document.getElementById('sidebarAccountMenu');if(legacyMenu){document.querySelectorAll('.nav-btn[data-view="support"]').forEach(x=>x.remove());return}const nav=document.querySelector('.nav-group:last-of-type');if(nav&&!nav.querySelector('[data-view="support"]')){const b=document.createElement('button');b.className='nav-btn';b.dataset.view='support';b.dataset.labelFa='پشتیبانی';b.dataset.labelEn='Support';b.innerHTML='<span class="nav-icon" data-icon="life-buoy" aria-hidden="true"></span><span class="nav-text">'+copy().title+'</span>';nav.appendChild(b);b.onclick=()=>setView('support');applyLucideIcons()}};
      const ensureView=()=>{if(document.getElementById('view-support'))return;const root=document.querySelector('.content');if(!root)return;const s=document.createElement('section');s.id='view-support';s.className='view';s.innerHTML='<div class="page-head"><div><h2 data-support-title></h2><p data-support-intro></p></div><button class="btn" data-support-refresh type="button"></button></div><div class="grid two-col"><div class="card section-card"><div class="section-title"><h3 data-support-new></h3></div><form data-support-form><div class="field"><label data-support-subject-label></label><input data-support-subject maxlength="200" required></div><div class="field"><label data-support-body-label></label><textarea data-support-body rows="6" maxlength="5000" required></textarea></div><div class="field"><label data-support-priority-label></label><select data-support-priority><option value="low"></option><option value="normal" selected></option><option value="high"></option><option value="urgent"></option></select></div><button class="btn primary" data-support-submit type="submit"></button></form></div><div class="card section-card"><div class="section-title"><h3 data-support-title-list></h3><span class="muted" data-support-count></span></div><div data-support-list class="detail-list"><div class="empty"></div></div></div></div>';root.appendChild(s);s.querySelector('[data-support-form]').onsubmit=createTicket;s.querySelector('[data-support-refresh]').onclick=loadTickets};
      const render=()=>{if(window.__supportV2Ready||window.__supportTicketV4)return;ensureNav();ensureView();const c=copy(),s=document.getElementById('view-support');if(!s)return;const set=(sel,v)=>{const el=s.querySelector(sel);if(el)el.textContent=v};set('[data-support-title]',c.title);set('[data-support-intro]',c.intro);set('[data-support-new]',c.newTitle);set('[data-support-subject-label]',c.subject);set('[data-support-body-label]',c.body);set('[data-support-priority-label]',c.priority);set('[data-support-submit]',c.submit);set('[data-support-refresh]',c.refresh);set('[data-support-title-list]',c.title);s.querySelector('[data-support-priority]')?.querySelectorAll('option').forEach(o=>o.textContent=c[o.value]);const list=s.querySelector('[data-support-list]');const tickets=state.supportTickets||[];s.querySelector('[data-support-count]').textContent=String(tickets.length);list.innerHTML=tickets.length?tickets.map(t=>{const can=Boolean(state.supportCanManage);const reply=can?'<textarea data-ticket-reply="'+esc(t.id)+'" rows="3" placeholder="'+esc(c.reply)+'"></textarea>':(t.owner_reply?'<p class="notice">'+esc(t.owner_reply)+'</p>':'');const controls=can?'<select data-ticket-status="'+esc(t.id)+'">'+['open','in_progress','waiting_user','resolved','closed'].map(x=>'<option value="'+x+'" '+(x===t.status?'selected':'')+'>'+esc(c[x])+'</option>').join('')+'</select><button class="btn small" data-ticket-save="'+esc(t.id)+'" type="button">'+esc(c.save)+'</button>':'';return '<article class="detail-item" data-ui-css="declaration-20"><div data-ui-css="declaration-21"><b>'+esc(t.subject)+'</b><span class="status">'+esc(c[t.status]||t.status)+'</span></div><small class="muted">'+esc(t.created_by||t.creator||'—')+' · '+esc(fmtDate(t.created_at))+' · '+esc(c[t.priority]||t.priority)+'</small><p>'+esc(t.body)+'</p>'+reply+(can?'<div class="actions" data-ui-css="declaration-7">'+controls+'</div>':'')+'</article>'}).join(''):'<div class="empty">'+esc(c.empty)+'</div>';list.querySelectorAll('[data-ticket-save]').forEach(b=>b.onclick=()=>updateTicket(b.dataset.ticketSave))};
      async function loadTickets(){if(window.__supportV2Ready||window.__supportTicketV4)return;ensureView();try{const data=await req('/admin/api/support/tickets');if(window.__supportTicketV4)return;state.supportTickets=data.my_tickets||data.tickets||[];state.supportMyTickets=state.supportTickets;state.supportAllTickets=data.all_tickets||state.supportTickets;state.supportCanManage=Boolean(data.can_manage);render()}catch(err){if(window.__supportTicketV4)return;state.supportTickets=[];state.supportMyTickets=[];state.supportAllTickets=[];toast(friendlyError(err.message),true)}}
      async function createTicket(event){event.preventDefault();const s=document.getElementById('view-support');const subject=s.querySelector('[data-support-subject]').value.trim(),body=s.querySelector('[data-support-body]').value.trim();if(!subject||!body){toast(state.language==='en'?'Enter subject and description.':'موضوع و شرح را وارد کنین.',true);return}try{await req('/admin/api/support/tickets',{method:'POST',body:JSON.stringify({subject,body,priority:s.querySelector('[data-support-priority]').value,assistant_id:state.assistantId||null})});event.target.reset();toast(state.language==='en'?'Ticket sent.':'تیکت ارسال شد.');await loadTickets()}catch(err){toast(friendlyError(err.message),true)}}
      async function updateTicket(id){const s=document.getElementById('view-support');try{await req('/admin/api/support/tickets/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({status:s.querySelector('[data-ticket-status="'+id+'"]')?.value,owner_reply:s.querySelector('[data-ticket-reply="'+id+'"]')?.value||''})});toast(state.language==='en'?'Ticket updated.':'تیکت به‌روزرسانی شد.');await loadTickets()}catch(err){toast(friendlyError(err.message),true)}}
      const oldSetView=window.setView;window.setView=function(name){ensureNav();ensureView();const result=oldSetView(name);if(name==='support')loadTickets();return result};const oldSetLanguage=window.setLanguage;window.setLanguage=function(lang){const result=oldSetLanguage(lang);render();window.__researchBeeUpgradeSupportTicket?.();if(document.getElementById('view-support')?.classList.contains('active'))loadTickets();return result};ensureNav();ensureView();render();window.loadSupportTickets=loadTickets;
    })();
