
    // MI-167/168: normalize News List rows and remove saved-view controls.
    (function(){
      const normalizeNews=()=>{document.querySelectorAll('#view-content .news-list-tools').forEach(node=>node.remove());const head=document.querySelector('#view-content thead tr');if(head){const label=window.__miLabel||((fa,en)=>state.language==='en'?en:fa),labels=[label('خبر','News'),label('وضعیت انتشار','Publication status'),label('امتیاز ارتباط','Relevancy score'),label('منبع خبر','News source'),label('تاریخ خبر','News date'),label('انتشار در تلگرام','Telegram publication')];const selectAll=head.querySelector('th[data-publication-select-all]');head.replaceChildren();if(selectAll)head.appendChild(selectAll);labels.forEach((x,i)=>{const th=document.createElement('th');th.dataset.publicationColumn=String(i);th.textContent=x;head.appendChild(th)})}document.querySelectorAll('#publicationRows tr').forEach(row=>{row.querySelectorAll('[data-feature-cell],[data-evidence-cell]').forEach(cell=>cell.remove());const hasSelect=Boolean(row.querySelector('td input[data-publication-id]'));const expected=hasSelect?7:6;while(row.querySelectorAll('td').length>expected)row.lastElementChild?.remove()})};
      const oldRender=window.renderPublications;if(typeof oldRender==='function'){window.renderPublications=function(){const result=oldRender.apply(this,arguments);normalizeNews();return result}}
      // renderPublications invokes normalizeNews after each table render.  A
      // subtree observer here duplicated that work for every row mutation and
      // repeatedly walked the news table while it was being enhanced.
      normalizeNews();
    })();
    // MI-170: owner-friendly theme cards while retaining the same preference API.
    (function(){
      const names={system:['System','همگام با سیستم'],light:['Light','روشن'],dark:['Dark','تیره'],honey:['Honey amber','عسل و کهربا'],default:['Attractive blue','آبی جذاب'],forest:['Forest green','جنگل سبز'],slate:['Faded gray','خاکستری محو'],blackyellow:['Black & yellow','مشکی و زرد'],red:['Professional red','قرمز حرفه‌ای']};
      const colors={system:'linear-gradient(135deg,#eef3fb 50%,#17243f 50%)',light:'#f8fafc',dark:'#17243f',honey:'#f5b942',default:'#2457d6',forest:'#237a57',slate:'#64748b',blackyellow:'linear-gradient(135deg,#111827 50%,#f5c542 50%)',red:'#c7364c'};
      function enhance(){const select=document.getElementById('appearanceTheme');if(!select||select.dataset.cardsReady==='1')return;select.dataset.cardsReady='1';const grid=document.createElement('div');grid.className='appearance-theme-grid';grid.setAttribute('role','radiogroup');for(const id of Object.keys(names)){const b=document.createElement('button');b.type='button';b.className='appearance-theme-card';b.dataset.theme=id;b.innerHTML='<span class="appearance-theme-swatch" data-theme-swatch="'+id+'"></span><b>'+names[id][state.language==='en'?0:1]+'</b><small>'+id+'</small>';b.onclick=()=>{select.value=id;select.dispatchEvent(new Event('change',{bubbles:true}));grid.querySelectorAll('.appearance-theme-card').forEach(x=>x.classList.toggle('active',x.dataset.theme===id))};grid.appendChild(b)}select.hidden=true;select.parentElement?.insertBefore(grid,select);grid.querySelectorAll('.appearance-theme-card').forEach(x=>x.classList.toggle('active',x.dataset.theme===select.value))}
      // Settings is the only surface that creates this custom theme grid.
      // Keep the observer local so normal page/table mutations do not wake it.
      new MutationObserver(enhance).observe(document.getElementById('view-settings')||document.body,{childList:true,subtree:true});enhance();
    })();
    // MI-172: Support lives in the account menu, not the primary sidebar.
    (function(){
      const ensure=()=>{document.querySelectorAll('.nav-btn[data-view="support"]').forEach(x=>x.remove());const menu=document.getElementById('sidebarAccountMenu');if(!menu)return;let b=menu.querySelector('[data-account-action="support"]');if(!b){b=document.createElement('button');b.type='button';b.dataset.accountAction='support';b.dataset.labelFa='پشتیبانی';b.dataset.labelEn='Support';b.setAttribute('role','menuitem');b.innerHTML='<span class="ui-icon" data-icon="life-buoy" aria-hidden="true"></span><span data-account-label></span>';menu.insertBefore(b,menu.querySelector('[data-account-action="logout"]'));b.addEventListener('click',e=>{e.stopPropagation();menu.hidden=true;window.setView?.('support')})}const label=b.querySelector('[data-account-label]');if(label)label.textContent=state.language==='en'?'Support':'پشتیبانی';applyLucideIcons()};ensure();
    })();
    // MI-171: guided ticket subjects, ticket identifiers and owner-routed replies.
    (function(){
      const categories=[['account_access','حساب و دسترسی','Account & access'],['project_setup','تعریف و تنظیم پروژه','Project setup'],['media_sources','رسانه و منابع','Media & sources'],['topics_analysis','موضوعات و تحلیل','Topics & analysis'],['schedule_publishing','زمان‌بندی و انتشار','Scheduling & publishing'],['telegram_whatsapp','تلگرام و واتس‌اپ','Telegram & WhatsApp'],['feedback_quality','بازخورد و کیفیت','Feedback & quality'],['billing_security','امنیت و امور مالی','Billing & security'],['other','سایر موضوعات','Other']];
      const optionMarkup=()=>categories.map(x=>'<option value="'+esc(x[0])+'">'+esc(localeLabel(x[1],x[2]))+'</option>').join('');
      const upgrade=()=>{const root=document.getElementById('view-support'),form=root?.querySelector('[data-support-form]');if(!root||!form)return;let select=form.querySelector('[data-support-category]'),other=form.querySelector('[data-support-other]');if(!select){const old=form.querySelector('[data-support-subject]');if(!old)return;form.dataset.guided='1';select=document.createElement('select');select.dataset.supportCategory='true';select.dataset.supportSubject='true';select.required=true;old.replaceWith(select);other=document.createElement('input');other.dataset.supportOther='true';other.maxLength=200;select.parentElement.appendChild(other);select.onchange=()=>{other.hidden=select.value!=='other';other.required=select.value==='other'};form.onsubmit=async e=>{e.preventDefault();const body=form.querySelector('[data-support-body]')?.value.trim()||'',category=select.value,subject=category==='other'?other.value.trim():'';if(body.length<10||(category==='other'&&subject.length<3)){toast(localeLabel('موضوع و شرح تیکت را کامل کنین.','Complete the ticket topic and description.'),true);return}try{await req('/admin/api/support/tickets',{method:'POST',body:JSON.stringify({category,other_subject:subject,body,priority:form.querySelector('[data-support-priority]')?.value||'normal',assistant_id:state.assistantId||null})});form.reset();other.hidden=true;toast(localeLabel('تیکت ثبت شد.','Ticket created.'));window.loadSupportTickets?.()}catch(err){toast(friendlyError(err.message),true)}}};const selected=select.value||'account_access';select.innerHTML=optionMarkup();select.value=categories.some(x=>x[0]===selected)?selected:'account_access';if(other){other.placeholder=localeLabel('عنوان تیکت را بنویسین','Write a ticket subject');other.hidden=select.value!=='other';other.required=select.value==='other'}};
      upgrade();window.__researchBeeUpgradeSupportTicket=upgrade;
    })();
    // MI-176/177/178: expose the secure source connector contract in the
    // existing source dialogs without duplicating the dialog implementation.
    (function(){
      const options=[['telegram_public','Telegram public'],['telegram_private','Telegram private'],['instagram_public','Instagram public'],['instagram_private','Instagram private'],['x_public','X public'],['x_private','X private']];
      const addField=(id,label,placeholder)=>{if(document.getElementById(id))return null;const input=document.createElement('input');input.id=id;input.maxLength=256;input.placeholder=placeholder||'';const wrap=document.createElement('div');wrap.className='field';const l=document.createElement('label');l.textContent=label;wrap.append(l,input);const grid=document.querySelector('#'+id.replace(/^df|^fSource/,'') )?.parentElement;return {input,wrap}};
      const ensure=()=>{['dfAdapter','fSourceAdapter'].forEach(id=>{const select=document.getElementById(id);if(!select)return;options.forEach(([value,label])=>{if(!select.querySelector('option[value="'+value+'"]')){const option=document.createElement('option');option.value=value;option.textContent=label;select.appendChild(option)}});const prefix=id==='dfAdapter'?'df':'f';const parent=select.closest('.form-grid');if(!parent)return;if(!parent.querySelector('#'+prefix+'AccessPolicy')){const policy=document.createElement('div');policy.className='field';policy.innerHTML='<label>Access policy</label><select id="'+prefix+'AccessPolicy"><option value="public_only">Public</option><option value="private_authenticated">Private / authenticated</option></select>';parent.appendChild(policy)}if(!parent.querySelector('#'+prefix+'CredentialRef')){const ref=document.createElement('div');ref.className='field';ref.innerHTML='<label>Credential reference (no secret)</label><input id="'+prefix+'CredentialRef" maxlength="128" placeholder="X_SOURCE_BEARER_TOKEN">';parent.appendChild(ref)}if(!parent.querySelector('#'+prefix+'AccountRef')){const account=document.createElement('div');account.className='field';account.innerHTML='<label>Account / channel reference</label><input id="'+prefix+'AccountRef" maxlength="256">';parent.appendChild(account)}})};
      const nativeFetch=window.fetch.bind(window);window.fetch=async(input,init={})=>{const url=typeof input==='string'?input:(input?.url||'');if(url.includes('/admin/api/')&&url.includes('/sources')&&init.body){try{const body=JSON.parse(init.body),select=document.getElementById('dfAdapter')||document.getElementById('fSourceAdapter'),prefix=document.getElementById('dfAdapter')?'df':'fSource',read=id=>document.getElementById(id)?.value?.trim()||null,adapter=select?.value||body.adapter||'';const policy=read(prefix+'AccessPolicy');if(adapter.endsWith('_private'))body.access_policy='private_authenticated';else if(policy)body.access_policy=policy;const ref=read(prefix+'CredentialRef'),account=read(prefix+'AccountRef');if(ref)body.credential_ref=ref;if(account)body.account_ref=account;init={...init,body:JSON.stringify(body)}}catch(_){}}return nativeFetch(input,init)};
      // Source dialogs are mounted under modalRoot; do not observe unrelated
      // dashboard mutations while waiting for a connector dialog.
      new MutationObserver(ensure).observe(document.getElementById('modalRoot')||document.body,{childList:true,subtree:true});ensure();
    })();
