
    /* MI-205: admin navigation and interaction quality pass.  The layer is
       intentionally progressive: if a legacy view is absent, that enhancement
       is skipped and the rest of the admin remains usable. */
    (function(){
      'use strict';
      // Ctrl/Cmd+K opens the command palette; the shortcut is discoverable in
      // the dialog and remains available on every authenticated Admin view.
      const doc=document,root=doc.documentElement,app=doc.getElementById('app'),shell=app,sidebar=doc.getElementById('sidebar'),toggle=doc.getElementById('mobileToggle');
      if(!app||!sidebar)return;
      const lang=()=>window.state?.language||'en',isFa=()=>lang()==='fa',text=(fa,en)=>isFa()?fa:en;
      const ownerOnlyLabels={fa:'فقط مالک',en:'Owners only',tr:'Yalnızca sahip',ar:'للمالك فقط',it:'Solo proprietario',es:'Solo propietario',de:'Nur Eigentümer',fr:'Propriétaire uniquement'};
      const ownerOnlyText=()=>ownerOnlyLabels[lang()]||ownerOnlyLabels.en;
      const palette=doc.getElementById('adminUxCommandPalette'),paletteSearch=doc.getElementById('adminUxCommandSearch'),paletteList=doc.getElementById('adminUxCommandList'),loadingBar=doc.getElementById('adminUxLoadingBar');
      const currentView=()=>doc.querySelector('.nav-btn.active')?.dataset.view||doc.querySelector('.view.active')?.id?.replace(/^view-/,'')||'overview';
      const navNodes=()=>[...doc.querySelectorAll('#sidebar .nav-btn[data-view]')];
      const navLabel=node=>{const label=lang()==='en'?node.dataset.labelEn:node.dataset.labelFa;return (label||node.querySelector('.nav-text')?.textContent||node.dataset.view||'').trim()};
      const commands=()=>{const seen=new Set();return navNodes().filter(node=>{const key=node.dataset.view;if(!key||seen.has(key))return false;seen.add(key);return true}).map(node=>({view:node.dataset.view,label:navLabel(node),icon:node.querySelector('.nav-icon')?.dataset.icon||'layout-dashboard'}))};
      let commandIndex=0,paletteOpener=null;
      const commandMatches=()=>{const query=(paletteSearch?.value||'').trim().toLocaleLowerCase();return commands().filter(item=>!query||item.label.toLocaleLowerCase().includes(query)||item.view.toLocaleLowerCase().includes(query))};
      const renderCommands=()=>{if(!paletteList)return;const items=commandMatches();commandIndex=Math.min(commandIndex,Math.max(0,items.length-1));paletteList.replaceChildren();if(!items.length){const empty=doc.createElement('div');empty.className='admin-ux-palette-empty';empty.textContent=text('صفحه‌ای با این عبارت پیدا نشد','No page matches this search');paletteList.appendChild(empty);return}items.forEach((item,index)=>{const button=doc.createElement('button');button.type='button';button.className='admin-ux-command';button.dataset.commandView=item.view;button.setAttribute('role','option');button.setAttribute('aria-selected',String(index===commandIndex));button.innerHTML='<span class="admin-ux-command-main"><span class="nav-icon" data-icon="'+item.icon+'" aria-hidden="true"></span><span></span></span><kbd>'+((index+1)<=9?index+1:'↵')+'</kbd>';button.querySelector('.admin-ux-command-main span:last-child').textContent=item.label;button.addEventListener('mouseenter',()=>{commandIndex=index;renderCommands()});button.addEventListener('click',()=>{openView(item.view);closePalette()});paletteList.appendChild(button)});try{window.applyLucideIcons?.()}catch(_){}};
      const openPalette=()=>{if(app.classList.contains('hidden'))return;if(palette.classList.contains('hidden'))paletteOpener=doc.activeElement;palette.classList.remove('hidden');palette.setAttribute('aria-hidden','false');commandIndex=0;renderCommands();requestAnimationFrame(()=>paletteSearch?.focus())};
      const closePalette=()=>{if(!palette||palette.classList.contains('hidden'))return;palette.classList.add('hidden');palette.setAttribute('aria-hidden','true');const opener=paletteOpener;paletteOpener=null;requestAnimationFrame(()=>{if(opener?.isConnected)opener.focus()})};
      const openView=name=>{try{if(typeof window.setView==='function')window.setView(name);else if(typeof setView==='function')setView(name)}catch(_){try{setView(name)}catch(__){}};persistView(name);syncHeader();animateActiveView()};
      const persistView=name=>{try{const url=new URL(location.href);url.searchParams.set('view',name);history.replaceState({view:name},'',url)}catch(_){}};
      const syncHeader=()=>{const active=currentView(),title=doc.getElementById('pageTitle'),context=doc.getElementById('pageContext');if(title)title.dataset.view=active;navNodes().forEach(node=>{if(node.dataset.view===active)node.setAttribute('aria-current','page');else node.removeAttribute('aria-current')});if(context){context.classList.add('admin-ux-context');const assistant=window.state?.assistants?.find(item=>item.id===window.state?.assistantId);context.textContent=assistant?.name||'';context.title=assistant?.name||'';context.hidden=!assistant?.name;context.setAttribute('aria-hidden',String(!assistant?.name))}};
      const animateActiveView=()=>{const view=doc.querySelector('.view.active');if(!view)return;view.classList.remove('admin-ux-view-enter');void view.offsetWidth;view.classList.add('admin-ux-view-enter')};
      const skeletonTargets=()=>[...doc.querySelectorAll('#app .view.active .kpi,#app .view.active .section-card,#app .view.active .assistant-card,#app .view.active .support-v4-card')].filter(node=>!node.closest('.modal,.drawer')&&node.offsetParent!==null);
      const showSkeletons=()=>{skeletonTargets().forEach(card=>{if(card.querySelector(':scope > .admin-ux-skeleton'))return;card.classList.add('admin-ux-skeleton-host');const layer=doc.createElement('div');layer.className='admin-ux-skeleton';layer.setAttribute('aria-hidden','true');layer.innerHTML='<span class="admin-ux-skeleton-line wide"></span><span class="admin-ux-skeleton-line medium"></span><span class="admin-ux-skeleton-block"></span><span class="admin-ux-skeleton-line short"></span>';card.appendChild(layer)})};
      const hideSkeletons=()=>{doc.querySelectorAll('.admin-ux-skeleton').forEach(layer=>layer.remove());doc.querySelectorAll('.admin-ux-skeleton-host').forEach(host=>host.classList.remove('admin-ux-skeleton-host'))};
      const markOwnerOnlyCards=()=>{const selectors=['#view-settings #limitsCard','#appearancePanel','#templateBuilderPanel'];selectors.forEach(selector=>doc.querySelectorAll(selector).forEach(card=>{card.dataset.ownerOnly='true';let head=card.querySelector(':scope > .section-title')||card.querySelector('.section-title');if(!head){head=doc.createElement('div');head.className='section-title';const title=doc.createElement('h3');title.textContent=doc.getElementById('limitsTitle')?.textContent||text('تنظیمات مالک','Owner settings');head.appendChild(title);card.prepend(head)}if(head.querySelector('.admin-ux-owner-badge'))return;const badge=doc.createElement('span');badge.className='admin-ux-owner-badge';badge.textContent=ownerOnlyText();badge.title=ownerOnlyText();badge.setAttribute('aria-label',ownerOnlyText());head.appendChild(badge)}))};
      const clearRefreshLabels=()=>{doc.getElementById('pipelineUpdated')?.replaceChildren();doc.getElementById('adminUxRefreshMeta')?.remove();doc.querySelectorAll('.admin-ux-refresh-meta').forEach(node=>node.remove())};
      const ownerObserver=new MutationObserver(()=>markOwnerOnlyCards());
      doc.querySelector('.content')&&ownerObserver.observe(doc.querySelector('.content'),{childList:true,subtree:true});
      const markLoading=(active)=>{if(active){showSkeletons();markOwnerOnlyCards()}else hideSkeletons();if(!loadingBar)return;loadingBar.classList.toggle('active',active);if(active)loadingBar.classList.remove('done');else{loadingBar.classList.add('done');setTimeout(()=>loadingBar.classList.remove('done'),380)}};
      const setCollapsed=collapsed=>{const value=Boolean(collapsed),before=currentView();app.classList.toggle('sidebar-collapsed',value);app.dataset.sidebarCollapsed=value?'true':'false';try{localStorage.setItem('research_bee_sidebar_collapsed',value?'1':'0')}catch(_){ }if(toggle){toggle.setAttribute('aria-expanded',String(!value));toggle.setAttribute('aria-pressed',String(value));toggle.setAttribute('aria-label',value?text('باز کردن منوی کناری','Expand sidebar'):text('جمع کردن منوی کناری','Collapse sidebar'));toggle.setAttribute('title',toggle.getAttribute('aria-label')||'')}requestAnimationFrame(()=>{if(currentView()===before)syncHeader();window.dispatchEvent(new Event('resize'));window.__researchBeeNormalizeButtons?.()})};
      const desktop=()=>window.matchMedia?.('(min-width:781px)').matches??window.innerWidth>780;
      try{if(desktop())setCollapsed(localStorage.getItem('research_bee_sidebar_collapsed')==='1')}catch(_){ }
      if(toggle){toggle.onclick=event=>{event.preventDefault();event.stopPropagation();if(desktop()){setCollapsed(!app.classList.contains('sidebar-collapsed'));return}const open=!sidebar.classList.contains('open');sidebar.classList.toggle('open',open);doc.getElementById('sidebarOverlay')?.classList.toggle('open',open);doc.getElementById('sidebarOverlay')?.setAttribute('aria-hidden',String(!open));toggle.setAttribute('aria-expanded',String(open))}};
      doc.querySelectorAll('[data-admin-ux-close-palette]').forEach(node=>node.addEventListener('click',closePalette));
      paletteSearch?.addEventListener('input',()=>{commandIndex=0;renderCommands()});
      doc.addEventListener('keydown',event=>{const typing=/INPUT|TEXTAREA|SELECT/.test(event.target?.tagName||'');if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();openPalette();return}if(palette&&!palette.classList.contains('hidden')){if(event.key==='Escape'){event.preventDefault();closePalette();return}if(event.key==='Tab'){const controls=[...palette.querySelectorAll('button:not([disabled]),input:not([disabled]),[href],[tabindex]:not([tabindex="-1"])')].filter(node=>node.getClientRects().length);if(controls.length){const first=controls[0],last=controls[controls.length-1];if(event.shiftKey&&(doc.activeElement===first||!palette.contains(doc.activeElement))){event.preventDefault();last.focus()}else if(!event.shiftKey&&(doc.activeElement===last||!palette.contains(doc.activeElement))){event.preventDefault();first.focus()}}else event.preventDefault();return}const items=commandMatches();if(event.key==='ArrowDown'&&items.length){event.preventDefault();commandIndex=(commandIndex+1)%items.length;renderCommands();return}if(event.key==='ArrowUp'&&items.length){event.preventDefault();commandIndex=(commandIndex-1+items.length)%items.length;renderCommands();return}if(event.key==='Enter'&&items[commandIndex]){event.preventDefault();openView(items[commandIndex].view);closePalette();return}return}if(event.key==='Escape'){closePalette();doc.getElementById('closeDrawer')?.click();return}if(!typing&&event.key==='/'){event.preventDefault();doc.getElementById('globalSearch')?.focus();return}if(!typing&&event.key==='?'){event.preventDefault();openPalette()}});
      doc.addEventListener('click',event=>{const viewTarget=event.target?.closest?.('[data-view]');if(viewTarget){markLoading(true);setTimeout(()=>markLoading(false),420);setTimeout(syncHeader,0)}const action=event.target?.closest?.('#refreshBtn,#systemRefreshBtn,#healthProbeBtn,#sourceProbeBtn,#runPipelineBtn,#operationsRunBtn,#saveScheduleBtn,#publicationFilterBtn');if(action){if(action.dataset.adminUxBusy==='1'){event.preventDefault();event.stopImmediatePropagation();return}action.dataset.adminUxBusy='1';action.classList.add('admin-ux-busy');action.setAttribute('aria-busy','true');markLoading(true);setTimeout(()=>{action.dataset.adminUxBusy='0';action.classList.remove('admin-ux-busy');action.removeAttribute('aria-busy');markLoading(false)},1500)}},true);

      const createRefreshMeta=()=>{clearRefreshLabels()};
      const markRefreshed=()=>{clearRefreshLabels()};
      /* Layout density is intentionally consistent across every admin view. */
      const filterConfigs=[['content','#publicationSearch','#publicationStatus','publicationFilterBtn'],['sources','#sourceSearch',null,null],['topics','#topicSearch',null,null]];
      const enhanceFilter=(viewId,searchSelector,statusSelector,filterButtonId)=>{const view=doc.getElementById('view-'+viewId),bar=view?.querySelector('.filter-bar');if(!bar||bar.dataset.adminUxEnhanced==='1')return;bar.dataset.adminUxEnhanced='1';bar.classList.add('admin-ux-sticky-toolbar');const summary=doc.createElement('div');summary.className='admin-ux-filter-summary';summary.setAttribute('aria-live','polite');bar.appendChild(summary);const search=doc.querySelector('#view-'+viewId+' '+searchSelector),status=statusSelector?doc.querySelector('#view-'+viewId+' '+statusSelector):null;const clear=doc.createElement('button');clear.type='button';clear.className='btn admin-ux-filter-clear';clear.textContent=text('پاک کردن فیلترها','Clear filters');clear.hidden=true;bar.insertBefore(clear,summary);const update=()=>{summary.replaceChildren();const values=[];if(search?.value.trim())values.push([text('جست‌وجو','Search'),search.value.trim(),()=>{search.value='';search.dispatchEvent(new Event('input',{bubbles:true}))}]);if(status?.value)values.push([text('وضعیت','Status'),status.options[status.selectedIndex]?.textContent||status.value,()=>{status.value='';status.dispatchEvent(new Event('change',{bubbles:true}))}]);values.forEach(([label,value,remove])=>{const chip=doc.createElement('span');chip.className='admin-ux-filter-chip';chip.textContent=label+': '+value;const x=doc.createElement('button');x.type='button';x.textContent='×';x.setAttribute('aria-label',text('حذف فیلتر','Remove filter'));x.addEventListener('click',remove);chip.appendChild(x);summary.appendChild(chip)});const visible=values.length>0;clear.hidden=!visible;clear.classList.toggle('is-visible',visible)};const save=()=>{try{localStorage.setItem('research_bee_admin_filter_'+viewId,JSON.stringify({search:search?.value||'',status:status?.value||''}))}catch(_){}};try{const saved=JSON.parse(localStorage.getItem('research_bee_admin_filter_'+viewId)||'{}');if(search&&saved.search)search.value=saved.search;if(status&&saved.status)status.value=saved.status}catch(_){ }search?.addEventListener('input',()=>{save();update()});status?.addEventListener('change',()=>{save();update()});clear.addEventListener('click',()=>{if(search)search.value='';if(status)status.value='';save();update();if(filterButtonId)doc.getElementById(filterButtonId)?.click();else if(viewId==='sources')window.renderSources?.();else if(viewId==='topics')window.renderTopics?.()});update()};
      const addCopyButtons=scope=>{scope.querySelectorAll?.('.detail-item b').forEach(node=>{if(node.querySelector('.admin-ux-copy'))return;const value=(node.textContent||'').trim();if(!/^(?:https?:\/\/|@|-?\d{5,}|[A-Za-z0-9_-]{12,})/.test(value)||value==='—')return;const button=doc.createElement('button');button.type='button';button.className='admin-ux-copy';button.title=text('کپی','Copy');button.setAttribute('aria-label',text('کپی مقدار','Copy value'));button.innerHTML='<span class="ui-icon" data-icon="copy" aria-hidden="true"></span>';button.addEventListener('click',async event=>{event.stopPropagation();try{await navigator.clipboard.writeText(value)}catch(_){const area=doc.createElement('textarea');area.value=value;area.style.position='fixed';area.style.opacity='0';doc.body.appendChild(area);area.select();doc.execCommand('copy');area.remove()}window.toast?.(text('مقدار کپی شد','Value copied'))});node.appendChild(button)});try{window.applyLucideIcons?.()}catch(_){}};
      const drawer=doc.getElementById('articleDrawer');if(drawer){const observer=new MutationObserver(()=>addCopyButtons(drawer));observer.observe(drawer,{subtree:true,childList:true});addCopyButtons(drawer)};
      let dirty=false;const guarded=event=>event.target?.closest?.('#view-schedule,#view-settings,#view-template-content,.modal');doc.addEventListener('input',event=>{if(guarded(event)){dirty=true;doc.querySelector('.admin-ux-dirty-indicator')?.classList.add('active')}});doc.addEventListener('click',event=>{if(event.target?.closest?.('#saveScheduleBtn,#saveLimitsBtn,#modalSubmit,[data-template-save]')){dirty=false;doc.querySelector('.admin-ux-dirty-indicator')?.classList.remove('active')}});window.addEventListener('beforeunload',event=>{if(!dirty)return;event.preventDefault();event.returnValue=''});
      const initialView=(()=>{try{return new URL(location.href).searchParams.get('view')}catch(_){return null}})();
      let initialViewApplied=false;
      const applyInitialView=()=>{if(initialViewApplied||app.classList.contains('hidden')||!window.state?.currentUser)return false;if(initialView&&commands().some(item=>item.view===initialView)&&currentView()!==initialView){initialViewApplied=true;openView(initialView);return true}initialViewApplied=true;return false};
      if(initialView)setTimeout(applyInitialView,0);const appGate=new MutationObserver(applyInitialView);appGate.observe(app,{attributes:true,attributeFilter:['class']});
      const baseSetView=window.setView;if(typeof baseSetView==='function'&&!baseSetView.__adminUxV325){const wrapped=function(name){const result=baseSetView.apply(this,arguments);persistView(name);setTimeout(()=>{syncHeader();animateActiveView()},0);return result};wrapped.__adminUxV325=true;window.setView=wrapped;try{setView=wrapped}catch(_){}}
      const baseLanguage=window.setLanguage;if(typeof baseLanguage==='function'&&!baseLanguage.__adminUxV325){const wrapped=function(language){const result=baseLanguage.apply(this,arguments);setTimeout(()=>{renderCommands();syncHeader();markOwnerOnlyCards();clearRefreshLabels();filterConfigs.forEach(config=>enhanceFilter(...config));const paletteInput=doc.getElementById('adminUxCommandSearch');if(paletteInput){paletteInput.placeholder=text('جست‌وجوی صفحه و عملیات','Search pages and actions');paletteInput.setAttribute('aria-label',paletteInput.placeholder)}},0);return result};wrapped.__adminUxV325=true;window.setLanguage=wrapped;try{setLanguage=wrapped}catch(_){} }
      const baseLoad=window.loadAll;if(typeof baseLoad==='function'&&!baseLoad.__adminUxV325){const wrapped=async function(){markLoading(true);try{return await baseLoad.apply(this,arguments)}finally{clearRefreshLabels();markOwnerOnlyCards();syncHeader();setTimeout(()=>markLoading(false),140)}};wrapped.__adminUxV325=true;window.loadAll=wrapped;try{loadAll=wrapped}catch(_){}}
      /* Legacy appearance preferences are intentionally ignored here. */
      filterConfigs.forEach(config=>enhanceFilter(...config));createRefreshMeta();markOwnerOnlyCards();syncHeader();clearRefreshLabels();renderCommands();try{window.applyLucideIcons?.()}catch(_){ }
      window.__researchBeeAdminUxV325={openPalette,closePalette,setCollapsed,markLoading,markRefreshed};
    })();
