/* Real HTTP/DB/browser E2E against news_chat_fixture.py, never production. */
import assert from 'node:assert/strict';
import {chromium} from 'playwright';
const base=process.env.BEE_CHAT_TEST_URL;
if(!base||process.env.MARKET_INTELLIGENCE_ENVIRONMENT!=='test')throw Error('Isolated synthetic app required');
// The controller shares the isolated app's network namespace and uses loopback.
// Clipboard is tested in a genuine trustworthy context without insecure flags.
assert.equal(new URL(base).hostname,'127.0.0.1','Loopback test context required');
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
await context.grantPermissions(['clipboard-read','clipboard-write'],{origin:new URL(base).origin});
const page=await context.newPage(),errors=[];
page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
const aid='10000000-0000-4000-8000-000000000001',pid='20000000-0000-4000-8000-000000000001',password='synthetic violet herons cross mountain lakes';
async function api(target,path,method='GET',body){return target.evaluate(async({path,method,body})=>{const name=path.startsWith('/admin')?'research_bee_admin_csrf=':'research_bee_user_csrf=';const csrf=document.cookie.split('; ').find(c=>c.startsWith(name))?.split('=').slice(1).join('=');const r=await fetch(path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':decodeURIComponent(csrf||'')},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json().catch(()=>({}))}},{path,method,body})}
async function login(target,user,admin=false){await target.goto(base+(admin?'/admin/login-up':'/user/login-up'));await target.locator(admin?'#loginUser':'#username').fill(user);await target.locator(admin?'#loginPass':'#password').fill(password);const result=target.waitForResponse(r=>r.url().endsWith((admin?'/admin':'/user')+'/api/login'));await target.locator(admin?'#loginSubmit':'#loginButton').click();const response=await result;assert.equal(response.status(),200,'Synthetic login failed: '+await response.text());try{await target.locator('#app:not(.hidden)').waitFor({timeout:10000})}catch(e){throw Error('Synthetic UI login: '+JSON.stringify({body:await response.json(),dom:await target.evaluate(()=>({error:document.querySelector('#loginError,#loginMsg')?.textContent,app:document.querySelector('#app')?.className,html:document.documentElement.className})),errors}))}}
async function open(){await page.locator(`.news-card[data-news-id="${pid}"] [data-action=open]`).click();await page.locator('#newsChat [type=submit]:not([disabled])').waitFor()}
async function ask(question){await page.locator('#news-chat-question').fill(question);await page.locator('#newsChat [type=submit]').click();await page.waitForFunction(()=>document.querySelector('.chat-turn')&&![...document.querySelectorAll('#newsChat .chat-status')].some(n=>n.textContent===window.BeeNewsChatI18n.t('running')||n.textContent===window.BeeNewsChatI18n.t('queued')));await page.locator('#newsChat [type=submit]:not([disabled])').waitFor()}
let ownerContext,owner;
try{
  for(let i=0;i<60;i++){try{if((await page.request.get(base+'/health')).ok())break}catch{}assert(i<59,'Test app did not become healthy');await page.waitForTimeout(250)}
  ownerContext=await browser.newContext();owner=await ownerContext.newPage();owner.on('pageerror',e=>errors.push(e.message));await login(owner,'chat-owner',true);
  assert.equal((await api(owner,'/meta')).data.environment,'test');assert.equal((await api(owner,'/meta')).data.pipeline.scheduler_enabled,false);
  const initialUsage=(await api(owner,'/admin/api/news-chat/usage')).data.requests.length;
  await owner.evaluate(()=>window.setView('account'));await owner.locator('#newsChatAdmin').waitFor();
  assert.equal(await owner.locator('#newsChatAdmin input[type=password]').count(),0);
  const originalPolicy=(await api(owner,'/admin/api/news-chat/policy')).data.policy;
  const savePolicy=owner.waitForResponse(r=>r.url().endsWith('/admin/api/news-chat/policy')&&r.request().method()==='PUT');await owner.locator('#newsChatAdmin button[type=submit]').click();assert.equal((await savePolicy).status(),200,'Owner policy form did not save');
  // Locale changes must not reset unsaved values, focus, or project selections.
  const ownerPanel=await owner.locator('#newsChatAdmin').elementHandle();
  await owner.locator('[data-chat-admin-label=globalBudget]').fill('12.34');
  await owner.locator('[data-chat-admin-label=project]').selectOption(aid);
  await owner.locator('[data-chat-admin-label=projectBudget]').fill('2.25');
  const allowedModels=owner.locator('#newsChatAdmin form > fieldset input[type=checkbox]');
  await allowedModels.first().uncheck();
  await owner.locator('.chat-model [data-chat-admin-label=label]').first().fill('Owner draft model');
  await owner.locator('.chat-model [data-chat-admin-label=label]').first().press('Tab');
  assert.equal(await allowedModels.first().isChecked(),false,'Editing a label silently granted an unchecked model');
  let policyReads=0;owner.on('request',r=>{if(r.url().endsWith('/admin/api/news-chat/policy')&&r.method()==='GET')policyReads++});
  await owner.locator('[data-chat-admin-label=globalBudget]').focus();
  for(const locale of ['fa','en','tr','ar','es','it','de','fr']){await owner.evaluate(locale=>{document.documentElement.lang=locale;document.documentElement.dir=['fa','ar'].includes(locale)?'rtl':'ltr'},locale);await owner.waitForFunction(()=>document.querySelector('#newsChatAdmin')?.dataset.locale===window.BeeNewsChatI18n.lang());assert.equal(await owner.locator('#newsChatAdmin h3').innerText(),await owner.evaluate(()=>window.BeeNewsChatI18n.t('settings')));assert(await owner.locator('#newsChatAdmin').evaluate(n=>n.scrollWidth<=n.clientWidth+2),'Owner form overflow: '+locale);assert(await ownerPanel.evaluate(n=>n.isConnected),'Locale replaced the policy form');assert.equal(await owner.locator('[data-chat-admin-label=globalBudget]').inputValue(),'12.34');assert.equal(await owner.locator('[data-chat-admin-label=projectBudget]').inputValue(),'2.25');assert.equal(await owner.locator('.chat-model [data-chat-admin-label=label]').first().inputValue(),'Owner draft model');assert.equal(await allowedModels.first().isChecked(),false);assert.equal(await owner.evaluate(()=>document.activeElement.dataset.chatAdminLabel),'globalBudget')}
  assert.equal(policyReads,0,'Locale caused a policy refetch over draft');
  await owner.locator('[data-chat-admin-label=project]').selectOption('10000000-0000-4000-8000-000000000002');await owner.locator('[data-chat-admin-label=projectBudget]').fill('3.25');await owner.locator('[data-chat-admin-label=project]').selectOption(aid);assert.equal(await owner.locator('[data-chat-admin-label=projectBudget]').inputValue(),'2.25');assert.equal(await allowedModels.first().isChecked(),false);
  const saveDraft=owner.waitForResponse(r=>r.url().endsWith('/admin/api/news-chat/policy')&&r.request().method()==='PUT');await owner.locator('#newsChatAdmin button[type=submit]').click();assert.equal((await saveDraft).status(),200);const draftPolicy=(await api(owner,'/admin/api/news-chat/policy')).data.policy;assert.equal(draftPolicy.daily_budget_usd,'12.34');assert.equal(draftPolicy.projects[aid].daily_budget_usd,'2.25');assert(!draftPolicy.projects[aid].model_keys.includes('openai:fixture-v1'));assert.equal(draftPolicy.models[0].label,'Owner draft model');assert.equal((await api(owner,'/admin/api/news-chat/policy','PUT',originalPolicy)).status,200);
  await owner.evaluate(()=>{document.documentElement.lang='en';document.documentElement.dir='ltr'});
  // Verify the actual account dialog, not only the dedicated grant endpoint.
  const accountRow=owner.locator('#accountsPanel tbody tr').filter({hasText:'chat-no-grant@gmail.com'});
  await accountRow.getByRole('button',{name:'Edit',exact:true}).click();
  let chatGrant=owner.getByLabel('Allow AI conversations in User',{exact:true});await chatGrant.check();
  let accountSave=owner.waitForResponse(r=>r.url().endsWith('/admin/api/accounts/30000000-0000-4000-8000-000000000004')&&r.request().method()==='PATCH'),accountReload=owner.waitForResponse(r=>r.url().includes('/admin/api/accounts?')&&r.request().method()==='GET');await owner.locator('.accounts-dialog').getByRole('button',{name:'Save',exact:true}).click();assert.equal((await accountSave).status(),200);await accountReload;await owner.waitForFunction(()=>!document.getElementById('accountsPanel').hasAttribute('aria-busy'));
  await accountRow.getByRole('button',{name:'Edit',exact:true}).click();chatGrant=owner.getByLabel('Allow AI conversations in User',{exact:true});assert(await chatGrant.isChecked(),'Account form did not persist chat grant');await chatGrant.uncheck();accountSave=owner.waitForResponse(r=>r.url().endsWith('/admin/api/accounts/30000000-0000-4000-8000-000000000004')&&r.request().method()==='PATCH');await owner.locator('.accounts-dialog').getByRole('button',{name:'Save',exact:true}).click();assert.equal((await accountSave).status(),200);
  const adminContext=await browser.newContext(),nonOwner=await adminContext.newPage();nonOwner.on('pageerror',e=>errors.push(e.message));await login(nonOwner,'chat-admin',true);assert.equal((await api(nonOwner,'/admin/api/news-chat/policy')).status,403);assert.equal((await api(nonOwner,'/admin/api/news-chat/users/30000000-0000-4000-8000-000000000004/grant','PUT',{enabled:true})).status,403);assert.equal((await api(nonOwner,'/admin/api/accounts/30000000-0000-4000-8000-000000000004','PATCH',{news_chat_access:true})).status,403);await nonOwner.evaluate(()=>window.setView('account'));assert.equal(await nonOwner.locator('#newsChatAdmin').count(),0);await adminContext.close();
  await login(page,'chat-reader');await page.locator(`.news-card[data-news-id="${pid}"]`).waitFor();await open();
  assert.equal((await api(page,'/user/api/publications/'+pid+'/detail')).data.source_name,'Synthetic source');
  assert.equal((await api(owner,'/admin/api/news-chat/usage')).data.requests.length,initialUsage,'Opening started paid generation');
  assert.equal(await page.getByRole('button',{name:'Stop response',exact:true}).isVisible(),false,'CSS overrode hidden for the inactive stop button');
  assert.equal(await page.locator('#newsChat .chat-suggestions button').count(),4);
  assert(await page.evaluate(()=>Object.values(window.BeeNewsChatI18n.words).every(values=>values.length===8&&values.every(value=>typeof value==='string'&&value.trim()))),'Incomplete chat locale catalog');
  for(const locale of ['fa','en','tr','ar','es','it','de','fr']){
    await page.evaluate(locale=>{document.documentElement.lang=locale;document.documentElement.dir=['fa','ar'].includes(locale)?'rtl':'ltr'},locale);
    await page.waitForFunction(()=>document.querySelector('#newsChat h3').textContent===window.BeeNewsChatI18n.t('chat'));
    assert.equal(await page.locator('#newsChat .chat-controls select').count(),4);
    for(const width of [1440,900,390,320]){
      await page.setViewportSize({width,height:1000});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const modal=page.locator('#newsDialog'),box=await modal.boundingBox();assert(box.x>=-1&&box.x+box.width<=width+1,`Modal overflow ${locale}/${width}: ${JSON.stringify(box)} ${await modal.evaluate(n=>JSON.stringify({width:getComputedStyle(n).width,container:getComputedStyle(n.parentElement).width,inline:n.getAttribute('style'),viewport:innerWidth,rules:[...document.styleSheets].flatMap(s=>[...s.cssRules].filter(r=>r.selectorText?.includes('#newsDialog')).map(r=>r.cssText))}))}`);assert(await modal.evaluate(n=>n.scrollWidth<=n.clientWidth+2),`Content overflow ${locale}/${width}`);
      if(width<=900){await page.locator('.chat-tabs [data-tab=chat]').click();assert(await page.locator('#newsChat').isVisible());assert.equal(await page.locator('#dialogBody').isVisible(),false);await page.locator('.chat-tabs [data-tab=news]').click();assert(await page.locator('#dialogBody').isVisible())}
      if(width===320){await page.locator('.chat-tabs [data-tab=news]').focus();await page.keyboard.press(['fa','ar'].includes(locale)?'ArrowLeft':'ArrowRight');assert.equal(await page.locator('.chat-tabs [data-tab=chat]').getAttribute('aria-selected'),'true');await page.keyboard.press('Home');assert.equal(await page.locator('.chat-tabs [data-tab=news]').getAttribute('aria-selected'),'true')}
      await page.locator('#closeDialog').focus();await page.keyboard.press('Shift+Tab');assert(await modal.evaluate(n=>n.contains(document.activeElement)),'Focus escaped modal');
    }
  }
  await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{document.documentElement.lang='en';document.documentElement.dir='ltr'});
  await page.evaluate(()=>{const p=document.getElementById('chat-report-1'),range=document.createRange();range.selectNodeContents(p);getSelection().removeAllRanges();getSelection().addRange(range)});await page.locator('#chat-selection').click();assert((await page.locator('#newsChat > .chat-status').innerText()).includes('Selected paragraph'));
  const selectedRequest=page.waitForRequest(r=>r.url().endsWith('/messages')&&r.method()==='POST');await ask('PRIVATE_OPENAI_HISTORY');assert.equal((await selectedRequest).postDataJSON().selected_segment,'report-1');assert((await page.locator('.chat-answer').last().innerText()).includes('Synthetic answer'));assert.equal(await page.getByRole('button',{name:'Stop response',exact:true}).isVisible(),false);
  for(const locale of ['fa','en','tr','ar','es','it','de','fr']){await page.evaluate(locale=>{document.documentElement.lang=locale;document.documentElement.dir=['fa','ar'].includes(locale)?'rtl':'ltr'},locale);await page.waitForFunction(()=>document.querySelector('#newsChat > .chat-status').textContent===window.BeeNewsChatI18n.t('completed'))}
  await page.evaluate(()=>{document.documentElement.lang='en';document.documentElement.dir='ltr';document.querySelector('.news-study-layout').scrollTop=100000});const closeBox=await page.locator('#closeDialog').boundingBox(),dialogBox=await page.locator('#newsDialog').boundingBox();assert(closeBox.y>=dialogBox.y&&closeBox.y+closeBox.height<=dialogBox.y+dialogBox.height,'Close button scrolled out of view');
  if(process.env.BEE_CHAT_ARTIFACT_DIR){const dir=process.env.BEE_CHAT_ARTIFACT_DIR;await page.evaluate(()=>document.querySelector('.news-study-layout').scrollTop=0);await page.screenshot({path:dir+'/news-chat-en-desktop.png'});await page.evaluate(()=>{document.documentElement.lang='fa';document.documentElement.dir='rtl'});await page.waitForFunction(()=>document.querySelector('#newsChat h3').textContent===window.BeeNewsChatI18n.t('chat'));await page.screenshot({path:dir+'/news-chat-fa-desktop.png'});await page.setViewportSize({width:390,height:1000});await page.locator('.chat-tabs [data-tab=chat]').click();assert.equal(await page.locator('.news-study-layout').evaluate(n=>n.scrollTop),0);await page.screenshot({path:dir+'/news-chat-fa-mobile.png'});await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>{document.documentElement.lang='en';document.documentElement.dir='ltr'});await page.waitForFunction(()=>document.querySelector('#newsChat h3').textContent==='Discuss this news')}
  assert.equal(await page.locator('.chat-turn').last().locator('.chat-citation').count(),1);
  await page.getByRole('button',{name:'Copy answer',exact:true}).last().click();assert.equal((await page.evaluate(()=>navigator.clipboard.readText())).trim(),(await page.locator('.chat-answer').last().innerText()).trim());
  await page.getByRole('button',{name:'Helpful',exact:true}).last().click();await page.waitForFunction(()=>document.querySelector('.chat-turn .chat-actions button[aria-pressed=true]')?.textContent===window.BeeNewsChatI18n.t('useful'));await page.getByRole('button',{name:'Not helpful',exact:true}).last().click();await page.waitForFunction(()=>document.querySelector('.chat-turn .chat-actions button[aria-pressed=true]')?.textContent===window.BeeNewsChatI18n.t('unhelpful'));
  await page.locator('.chat-turn').last().locator('.chat-citation').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'chat-report-1',await page.evaluate(()=>JSON.stringify({status:document.querySelector('#newsChat > .chat-status')?.textContent,body:document.getElementById('dialogBody').innerHTML,focus:document.activeElement.outerHTML.slice(0,150)})));
  await page.getByRole('button',{name:'Save to note',exact:true}).last().click();await page.waitForFunction(()=>document.getElementById('dialogNote').value.includes('Synthetic answer'));
  const note=await api(page,'/user/api/assistants/'+aid+'/reading-state');assert.equal(note.status,200);assert(JSON.stringify(note.data).includes('Synthetic answer'));
  assert(JSON.stringify(note.data).includes('openai fixture model'),'Saved note lost model provenance');assert(JSON.stringify(note.data).includes('report-1'),'Saved note lost report reference');assert(JSON.stringify(note.data).includes('/user/news/'+pid),'Saved note lost source report link');
  let list=(await api(page,'/user/api/publications/'+pid+'/conversations')).data.conversations;assert.equal(list.length,1);const first=list[0].id;
  assert.equal((await api(page,'/user/api/conversations/'+first+'/messages')).data.messages.at(-1).feedback,-1,'Answer feedback did not persist');
  // Same idempotency key returns one row, even concurrent submissions.
  const ctx=(await api(page,'/user/api/publications/'+pid+'/chat-context')).data;
  const q={question:'Idempotency test',model_key:'openai:fixture-v1',language:'en',context_version:ctx.version,idempotency_key:'browser-unique-fixture-00001'};
  const [a,b]=await Promise.all([api(page,'/user/api/conversations/'+first+'/messages','POST',q),api(page,'/user/api/conversations/'+first+'/messages','POST',q)]);assert.equal(a.status,202);assert.equal(b.status,202);assert.equal(a.data.id,b.data.id);
  await page.waitForTimeout(1000);
  await page.locator('#newsChat .chat-controls select').nth(0).selectOption('anthropic');assert((await page.locator('#newsChat').innerText()).includes('Provider changed'));
  await ask('Claude question');list=(await api(page,'/user/api/publications/'+pid+'/conversations')).data.conversations;assert.equal(list.length,2);assert.equal(list[0].provider,'anthropic');
  await page.locator('#newsChat .chat-controls select').nth(0).selectOption('google');await ask('Gemini question');assert.equal((await page.locator('.chat-turn').last().innerText()).includes('Google'),true);
  await page.locator('#news-chat-question').fill('SLOW');await page.locator('#newsChat [type=submit]').click();await page.getByRole('button',{name:'Stop response',exact:true}).waitFor();await page.getByRole('button',{name:'Stop response',exact:true}).click();await page.locator('#newsChat [type=submit]:not([disabled])').waitFor();assert((await page.locator('#newsChat').innerText()).includes('Response stopped'));
  // A different synthetic user keeps this phase within the real 5/minute limit.
  const failingContext=await browser.newContext(),failing=await failingContext.newPage();failing.on('pageerror',e=>errors.push(e.message));await login(failing,'chat-other');await failing.locator('.news-card [data-action=open]').first().click();await failing.locator('#newsChat [type=submit]:not([disabled])').waitFor();await failing.locator('#news-chat-question').fill('FAIL');await failing.locator('#newsChat [type=submit]').click();await failing.waitForFunction(()=>document.querySelector('.chat-turn')?.textContent.includes(window.BeeNewsChatI18n.t('error')));await failing.waitForTimeout(500);assert((await failing.locator('.chat-turn').last().innerText()).includes('Request failed'));
  await failing.getByRole('button',{name:'Try again; may incur a charge',exact:true}).last().click();assert.equal(await failing.locator('#news-chat-question').inputValue(),'FAIL');
  await failing.locator('#news-chat-question').fill('HANG');await failing.locator('#newsChat [type=submit]').click();await failing.getByRole('button',{name:'Stop response',exact:true}).waitFor();await failing.waitForTimeout(1000);await failing.getByRole('button',{name:'Stop response',exact:true}).click();await failing.locator('#newsChat [type=submit]:not([disabled])').waitFor({timeout:3000});assert((await failing.locator('#newsChat').innerText()).includes('Response stopped'),'No-token upstream did not stop promptly');
  // The server accepts a paid job, but its HTTP acknowledgement is lost.
  // A manual retry of the retained draft must recover that same job, not pay twice.
  const beforeLostAck=(await api(owner,'/admin/api/news-chat/usage')).data.requests.length;let lostId=null,dropOnce=true;
  await failing.route('**/user/api/conversations/*/messages',async route=>{if(route.request().method()==='POST'&&route.request().postDataJSON().question==='ACK_LOSS'&&dropOnce){dropOnce=false;const response=await route.fetch();assert.equal(response.status(),202);lostId=(await response.json()).id;await route.abort('failed')}else await route.continue()});
  await failing.locator('#news-chat-question').fill('ACK_LOSS');await failing.locator('#newsChat [type=submit]').click();await failing.waitForFunction(()=>document.getElementById('news-chat-question').value==='ACK_LOSS'&&document.querySelector('#newsChat .chat-composer .chat-error').textContent.includes(window.BeeNewsChatI18n.t('error'))&&!document.querySelector('#newsChat [type=submit]').disabled);assert(lostId);
  await failing.locator('#newsChat [type=submit]').click();await failing.waitForFunction(id=>document.querySelector(`[data-generation="${id}"] .chat-answer`)?.textContent.includes('Synthetic answer')&&!document.querySelector('#newsChat [type=submit]').disabled,lostId);assert.equal((await api(owner,'/admin/api/news-chat/usage')).data.requests.length,beforeLostAck+1,'Lost acknowledgement created a duplicate paid job');await failingContext.close();
  // Private history and project ACL checked with independent real sessions.
  for(const name of ['chat-other','chat-no-grant']){const isolated=await browser.newContext(),other=await isolated.newPage();other.on('pageerror',e=>errors.push(e.message));await login(other,name);assert.equal((await api(other,'/user/api/conversations/'+first+'/messages')).status,name==='chat-other'?404:403);assert.equal((await api(other,'/user/api/publications/'+pid+'/chat-context')).status,name==='chat-other'?404:403);assert.equal(await other.locator('#newsChatAdmin').count(),0);assert.equal((await api(other,'/admin/api/news-chat/policy')).status,401);if(name==='chat-no-grant'){const modelCheck=other.waitForResponse(r=>r.url().includes('/user/api/chat/models?'));await other.locator('.news-card [data-action=open]').first().click();assert.equal((await modelCheck).status(),403);for(const width of [1440,390]){await other.setViewportSize({width,height:1000});assert(await other.locator('#dialogBody').isVisible(),'Chat grant was required to read news');assert.equal(await other.locator('#newsChat').isVisible(),false);assert.equal(await other.locator('.chat-tabs').isVisible(),false);assert.equal(await other.locator('#chat-selection').isVisible(),false)}}await isolated.close()}
  // Opt-out must preserve the existing reader, including mobile layout.
  const offContext=await browser.newContext(),offReader=await offContext.newPage();await login(offReader,'chat-reader');const offPolicy={...originalPolicy,enabled:false};assert.equal((await api(owner,'/admin/api/news-chat/policy','PUT',offPolicy)).status,200);const offCheck=offReader.waitForResponse(r=>r.url().includes('/user/api/chat/models?'));await offReader.locator('.news-card [data-action=open]').first().click();assert.equal((await offCheck).status(),200);for(const width of [1440,390]){await offReader.setViewportSize({width,height:1000});assert(await offReader.locator('#dialogBody').isVisible());assert.equal(await offReader.locator('#newsChat').isVisible(),false);assert.equal(await offReader.locator('.chat-tabs').isVisible(),false)}await offContext.close();assert.equal((await api(owner,'/admin/api/news-chat/policy','PUT',originalPolicy)).status,200);
  assert.equal((await api(page,'/user/api/publications/20000000-0000-4000-8000-000000000003/chat-context')).status,404);
  const beforeDelete=(await api(owner,'/admin/api/news-chat/usage')).data.requests.length;await page.getByRole('button',{name:'Delete conversation',exact:true}).click();assert.equal((await api(owner,'/admin/api/news-chat/usage')).data.requests.length,beforeDelete,'Deletion reset spend ledger');
  // Back/filter preservation, direct links and focus restoration.
  await page.locator('#closeDialog').click();assert.equal(new URL(page.url()).pathname,'/user');await page.goto(base+'/user/news/'+pid);await page.locator('#newsChat [type=submit]:not([disabled])').waitFor();await page.locator('#closeDialog').click();assert.equal(new URL(page.url()).pathname,'/user');
  await page.locator('#mobileMenuButton').click();assert(await page.locator('#app').evaluate(n=>n.classList.contains('sidebar-collapsed')));await open();await page.keyboard.press('Escape');assert.equal(await page.locator('#dialogBackdrop').evaluate(n=>n.classList.contains('hidden')),true);
  // Server-enforced budget, not merely a disabled UI control.
  const policy=(await api(owner,'/admin/api/news-chat/policy')).data.policy;const reduced=structuredClone(policy);reduced.user_daily_budget_usd='0.00000001';assert.equal((await api(owner,'/admin/api/news-chat/policy','PUT',reduced)).status,200);
  const c=(await api(page,'/user/api/publications/'+pid+'/conversations','POST',{model_key:'openai:fixture-v1'})).data;
  assert.equal((await api(page,'/user/api/conversations/'+c.id+'/messages','POST',{...q,idempotency_key:'browser-budget-fixture-00001'})).status,429);
  assert.equal((await api(owner,'/admin/api/news-chat/policy','PUT',policy)).status,200);
  // Grant revocation kills the reader session and further delivery.
  assert.equal((await api(owner,'/admin/api/news-chat/users/30000000-0000-4000-8000-000000000002/grant','PUT',{enabled:false})).status,200);assert.equal((await api(page,'/user/api/me')).status,401);
  const revokedContext=await browser.newContext(),revoked=await revokedContext.newPage();revoked.on('pageerror',e=>errors.push(e.message));await login(revoked,'chat-other');await revoked.locator('.news-card [data-action=open]').first().click();await revoked.locator('#newsChat [type=submit]:not([disabled])').waitFor();await revoked.locator('#news-chat-question').fill('SLOW');await revoked.locator('#newsChat [type=submit]').click();await revoked.getByRole('button',{name:'Stop response',exact:true}).waitFor();assert.equal((await api(owner,'/admin/api/news-chat/users/30000000-0000-4000-8000-000000000003/grant','PUT',{enabled:false})).status,200);await revoked.waitForFunction(()=>document.querySelector('#newsChat .chat-composer .chat-error').textContent===window.BeeNewsChatI18n.t('expired'));assert.equal(await revoked.locator('#newsChat .chat-turn').count(),0,'Revoked session retained private conversation text');assert.equal(await revoked.locator('#news-chat-question').inputValue(),'');assert(await revoked.locator('#newsChat [type=submit]').isDisabled(),'Expired session still offered sending');await revokedContext.close();
  assert.deepEqual(errors,[]);
  console.log('News chat E2E passed: strict CSP, real DB/API/worker/SSE, no call on open, 3 synthetic providers, private/project ACL, 8 locales × 4 widths, owner draft/focus/unchecked grants preserved across languages, real account grant dialog and non-owner admin refusal, citations/notes with model provenance, atomic idempotency and lost-ack recovery without duplicate billing, stop/error/delete, preserved ledger, direct links/back/focus/sidebar, disabled/ungranted reader compatibility, budget refusal and grant revocation. No live provider calls.');
}finally{await ownerContext?.close();await context.close();await browser.close()}
