(() => {
  'use strict';
  const I=window.BeeReportI18n,t=I.t,$=id=>document.getElementById(id);
  let user=null,businesses=[],business=null,report=null,dirty=false,tab='new',next=null,poll=null,returnFocus=null,draftKey=null;
  const pendingRequests=new Set();let listGeneration=0;
  const names={en:'English',fa:'فارسی',tr:'Türkçe',ar:'العربية',es:'Español',it:'Italiano',de:'Deutsch',fr:'Français'};
  function identifier(){const a=crypto.getRandomValues(new Uint8Array(16));a[6]=(a[6]&15)|64;a[8]=(a[8]&63)|128;const h=[...a].map(v=>v.toString(16).padStart(2,'0')).join('');return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20);}
  function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
  function btn(key,fn,cls=''){const n=el('button',t(key),'report-btn '+cls);n.type='button';n.onclick=()=>act(n,fn);return n;}
  function message(key,error=false){$('reportMessage').textContent=t(key);$('reportMessage').classList.toggle('error',error);$('reportMessage').hidden=false;if(error&&$('reportDialog').open){$('reportDialogError')?.remove();const n=el('p',t(key),'error');n.id='reportDialogError';n.setAttribute('role','alert');$('reportDialogContent').append(n);}}
  function errorKey(e){const c=e.code||'';if(c.includes('consent'))return 'consentError';if(c.includes('confidential'))return 'blocked';if(c.includes('revision'))return 'conflict';if(e.status===429)return 'limitError';if(e.status===422)return 'invalidField';if(e.status===409||e.status===503)return 'setupError';return 'error';}
  async function api(path,method='GET',data){const controller=new AbortController();pendingRequests.add(controller);try{const r=await fetch('/report/api'+path,{method,signal:controller.signal,credentials:'same-origin',headers:{'Content-Type':'application/json','X-User-Activity':method==='GET'?'0':'1'},body:data===undefined?undefined:JSON.stringify(data)});let v={};try{v=await r.json();}catch{}if(!r.ok){if(r.status===401){showLogin();}const e=new Error('request_failed');e.status=r.status;e.code=v.detail;e.fields=v.fields;throw e;}return v;}finally{pendingRequests.delete(controller);}}
  async function act(button,fn){if(!$('reportDialog').open)returnFocus=button;button.disabled=true;try{await fn();}catch(e){if(!user||e.name==='AbortError')return;message(errorKey(e),true);const form=$('reportForm');if(form&&!$('reportDialog').open&&Array.isArray(e.fields)){for(const name of e.fields){const input=form.elements.namedItem(name);if(input?.setCustomValidity){input.setCustomValidity(t('invalidField'));input.setAttribute('aria-invalid','true');input.closest('details')?.setAttribute('open','');}}form.reportValidity();}}finally{button.disabled=false;}}
  function help(key){const wrap=el('span',undefined,'report-help'),b=el('button','i');b.type='button';b.setAttribute('aria-label',t(key));const tip=el('span',t(key));tip.id='tip-'+identifier();tip.setAttribute('role','tooltip');b.setAttribute('aria-describedby',tip.id);b.onclick=()=>wrap.classList.toggle('open');b.onkeydown=e=>{if(e.key==='Escape')wrap.classList.remove('open');};wrap.append(b,tip);return wrap;}
  function field(key,input,info,wide=false){const l=el('div',undefined,'report-field'+(wide?' report-wide':'')),s=el('span'),label=el('label',t(key));input.id='field-'+key;label.htmlFor=input.id;s.append(label);if(info)s.append(help(info));l.append(s,input);return l;}
  function input(name,value='',type='text'){const n=el('input');n.name=name;n.type=type;n.value=value;return n;}
  function select(name,items,value){const n=el('select');n.name=name;for(const [id,label]of items){const o=el('option',label);o.value=id;n.append(o);}if(value)n.value=value;return n;}
  function discard(){return !dirty||confirm(t('unsaved'));}
  function showLogin(){clearInterval(poll);for(const controller of pendingRequests)controller.abort();pendingRequests.clear();listGeneration++;user=null;businesses=[];business=null;report=null;dirty=false;tab='new';next=null;draftKey=null;returnFocus=null;if($('reportDialog').open)$('reportDialog').close();for(const id of ['reportCompose','reportList','reportScope','reportDialogContent','reportAccount'])$(id).replaceChildren();$('reportMessage').hidden=true;$('reportMessage').textContent='';$('app').classList.add('hidden');$('login').classList.remove('hidden');document.documentElement.classList.remove('session-checking');document.documentElement.dataset.theme='honey';loginLocale();}
  function showApp(){document.documentElement.dataset.theme='light';$('app').classList.remove('hidden');$('login').classList.add('hidden');document.documentElement.classList.remove('session-checking');render();}
  function render(){document.documentElement.lang=I.lang;document.documentElement.dir=['fa','ar'].includes(I.lang)?'rtl':'ltr';$('reportHeading').replaceChildren(el('span',t('portal')),help('privateHelp'));$('reportAccount').textContent=user.display_name;$('reportLogout').textContent=t('signOut');const lang=select('',Object.entries(names),I.lang);$('reportLanguage').replaceChildren(...lang.children);$('reportLanguage').value=I.lang;$('reportLanguage').onchange=e=>{if(!discard()){e.target.value=I.lang;return;}I.set(e.target.value);dirty=false;render();};const nav=$('reportNavigation');nav.replaceChildren();for(const [id,key]of [['new','newReport'],['list','myReports']]){const b=btn(key,()=>navigate(id));b.setAttribute('aria-current',tab===id?'page':'false');nav.append(b);}scope();compose();$('reportCompose').classList.toggle('hidden',tab!=='new');$('reportList').classList.toggle('hidden',tab!=='list');if(tab==='list')loadList().catch(e=>message(errorKey(e),true));}
  function scope(){const host=$('reportScope');host.replaceChildren();if(!business)return;const choice=select('business',businesses.map(b=>[b.id,b.name]),business.id);choice.onchange=()=>{if(!discard()){choice.value=business.id;return;}business=businesses.find(b=>b.id===choice.value);report=null;draftKey=null;dirty=false;render();};if(businesses.length>1)host.append(field('business',choice,'scopeHelp'));else host.append(el('strong',business.name));if(business.role==='manager')host.append(btn('consent',consentDialog));}
  function currentValue(){if(!report)return {};return report.versions.find(v=>v.id===report.current_version_id)||{};}
  function compose(){
    const host=$('reportCompose');host.replaceChildren();
    if(!business||!business.projects.length){host.append(el('p',t('setupError')));return;}
    const v=currentValue(),form=el('form');form.id='reportForm';
    const grid=el('div',undefined,'report-grid');
    const p=select('assistant_id',business.projects.map(p=>[p.id,p.name]),report?.assistant_id);p.required=true;
    if(business.projects.length===1){p.hidden=true;grid.append(p,el('strong',t('project')+' · '+business.projects[0].name,'report-wide'));}
    else grid.append(field('project',p,'scopeHelp',true));
    const title=input('title',v.title);title.required=true;title.minLength=5;title.maxLength=200;grid.append(field('title',title,'titleHelp',true));
    const text=el('textarea');text.name='text';text.value=v.text||'';text.required=true;text.minLength=50;text.dir='auto';grid.append(field('text',text,'textHelp',true));
    const counter=el('div',undefined,'report-count report-wide');const count=()=>counter.textContent=text.value.length.toLocaleString(I.lang)+' / '+text.maxLength.toLocaleString(I.lang);text.addEventListener('input',count);grid.append(counter);
    const tag=input('tags',(v.tags||[]).join(', '));tag.maxLength=310;tag.required=true;const options=el('datalist');options.id='reportTagOptions';tag.setAttribute('list',options.id);grid.append(field('tags',tag,'tagsHelp'),options);
    const name=input('reporter',v.reporter||user.display_name);name.required=true;name.maxLength=160;grid.append(field('reporter',name,'reporterHelp'));form.append(grid);
    const extra=el('details'),optional=el('div',undefined,'report-grid');extra.append(el('summary',t('optional')));
    optional.append(field('date',input('event_date',v.event_date,'date'),'dateHelp'),field('language',select('language',Object.entries(names),v.language||I.lang),'languageHelp'),field('classification',select('classification',['internal','confidential','very_confidential'].map(k=>[k,t(k)]),v.classification),'blocked',true));extra.append(optional);form.append(extra);
    const sync=()=>{const project=business.projects.find(x=>x.id===p.value);text.maxLength=project?.text_limit||20000;options.replaceChildren(...(project?.tags||[]).map(v=>{const o=el('option');o.value=v;return o;}));count();};p.addEventListener('change',sync);sync();
    const actions=el('div',undefined,'report-actions');actions.append(btn('save',()=>save(form)),btn('preview',()=>preview(form),'primary'));form.append(actions);form.oninput=e=>{dirty=true;if(e.target.setCustomValidity){e.target.setCustomValidity('');e.target.removeAttribute('aria-invalid');}};form.onsubmit=e=>e.preventDefault();host.append(el('h2',t('newReport')),form);
    if(v.sealed){for(const n of form.elements)n.disabled=true;actions.replaceChildren(btn('revise',async()=>{await api('/reports/'+report.id+'/revise','POST',{});report=await api('/reports/'+report.id);compose();}));}
  }
  function values(form){const f=new FormData(form);if(!draftKey)draftKey=identifier();return {draft_key:draftKey,business_id:business.id,assistant_id:f.get('assistant_id'),title:f.get('title'),text:f.get('text'),tags:String(f.get('tags')||'').split(/[,،]/).map(s=>s.trim()).filter(Boolean),reporter:f.get('reporter'),event_date:f.get('event_date'),language:f.get('language'),classification:f.get('classification'),revision:currentValue().revision||0};}
  async function save(form){if(!form.reportValidity())return false;const r=await api('/reports'+(report?'/'+report.id:''),report?'PUT':'POST',values(form));report=await api('/reports/'+r.id);dirty=false;message('saved');return true;}
  function openDialog(key){$('reportDialogHeading').textContent=t(key);$('reportDialogContent').replaceChildren();$('reportDialogClose').textContent=t('close');if(!$('reportDialog').open)$('reportDialog').showModal();return $('reportDialogContent');}
  function section(host,key,text){const s=el('section');if(key==='connection'&&!text)text=t('noBusinessContext');s.append(el('h3',t(key)),el('div',text,'report-prose'));host.append(s);}
  async function preview(form){if(!await save(form))return;const value=currentValue(),host=openDialog('preview'),project=business.projects.find(p=>p.id===report.assistant_id);const meta=el('dl',undefined,'report-metadata');for(const [key,v]of [['business',business.name],['project',project?.name||''],['models',project?.model||''],['language',names[value.language]],['classification',t(value.classification)],['reporter',value.reporter]]){meta.append(el('dt',t(key)),el('dd',v));}host.append(meta);section(host,'title',value.title);section(host,'text',value.text);host.append(el('p',t('privateHelp')),el('p',t('disclosure')));if(value.classification==='very_confidential'){host.append(el('p',t('blocked')));return;}const ack=input('', '', 'checkbox'),check=el('label',undefined,'report-check');check.append(ack,el('span',t('submit')));host.append(check);const key=identifier();const send=btn('submit',async()=>{if(!ack.checked){ack.focus();return;}await api('/reports/'+report.id+'/submit','POST',{idempotency_key:key,revision:currentValue().revision,confirmed:true});$('reportDialog').close();dirty=false;message('queued');report=null;draftKey=null;await navigate('list');},'primary');host.append(send);}
  async function navigate(id){if(!discard())return;tab=id;dirty=false;if(id==='new'){report=null;draftKey=null;}render();}
  async function loadList(append=false){const host=$('reportList');if(!business){host.replaceChildren(el('p',t('setupError')));return;}const generation=++listGeneration,businessId=business.id;if(!append){host.replaceChildren();const h=el('div',undefined,'report-list-head');h.append(el('h2',t('myReports')),btn('refresh',()=>loadList()));host.append(h);const list=el('div',undefined,'report-list-items');list.id='reportListItems';for(let i=0;i<6;i++)list.append(el('div',undefined,'report-skeleton'));host.append(list);}const page=await api('/reports?business_id='+businessId+(append?'&offset='+next:''));if(!user||tab!=='list'||business?.id!==businessId||generation!==listGeneration)return;const list=$('reportListItems');if(!list)return;if(!append)list.replaceChildren();for(const r of page.items){const c=el('button',undefined,'report-list-card');c.type='button';c.append(el('strong',r.title),el('span',t(r.state==='queued'?'queued':r.state),'report-badge '+r.state),el('time',new Date(r.created_at).toLocaleString(I.lang)));c.onclick=()=>act(c,()=>openReport(r.id));list.append(c);}if(!list.children.length)list.append(el('p',t('empty')));next=page.next_offset;$('reportMore')?.remove();if(next!==null){const b=btn('more',()=>loadList(true));b.id='reportMore';host.append(b);}}
  async function openReport(id){const data=await api('/reports/'+id),host=openDialog('myReports');host.append(el('p',t('privateHelp')));for(const v of [...data.versions].reverse()){const version=el('details',undefined,'report-version');version.open=v.id===data.current_version_id;version.append(el('summary',t('version')+' '+v.number+' · '+v.title));section(version,'original',v.text);for(const job of data.jobs.filter(j=>j.version_id===v.id)){version.append(el('h3',t(job.status==='queued'?'queued':job.status)));if(job.status==='failed')version.append(el('p',t(errorKey({code:job.error_code}))));if(job.result){const r=job.result;version.append(el('p',t(r.relevance.relevance_state)));for(const [key,field]of [['summary','news_summary'],['connection','business_connection'],['opportunity','opportunity'],['risk','risk'],['action','suggested_action']])section(version,key,r.analysis[field]||'');section(version,'facts',(r.analysis.facts||[]).join('\n'));section(version,'inferences',(r.analysis.inferences||[]).join('\n'));for(const score of r.topic_scores){version.append(el('p',score.topic_key+': '+score.score.toFixed(2)+' / '+score.threshold.toFixed(2)));section(version,'evidence',(score.evidence||[]).join('\n'));}section(version,'connection',r.business_assessment.reason||'');version.append(el('small',r.model));}}host.append(version);}const actions=el('div',undefined,'report-actions');actions.append(btn('delete',async()=>{if(!confirm(t('deleteAsk')))return;await api('/reports/'+id,'DELETE');$('reportDialog').close();await loadList();},'danger'));if(data.can_edit){if(data.state==='draft')actions.append(btn('newReport',()=>{report=data;draftKey=id;tab='new';$('reportDialog').close();render();},'primary'));else if(!data.jobs.some(j=>['running','queued'].includes(j.status)))actions.append(btn('revise',async()=>{await api('/reports/'+id+'/revise','POST',{});report=await api('/reports/'+id);draftKey=id;tab='new';$('reportDialog').close();render();},'primary'));}host.append(actions);}
  function consentDialog(){const host=openDialog('consent');host.append(el('p',t('disclosure')));const modelHost=el('div'),chosen=[];for(const model of business.models){const c=input('', '', 'checkbox');c.checked=(business.policy.models||[]).includes(model);chosen.push([model,c]);const label=el('label',undefined,'report-check');label.append(c,el('span',model));modelHost.append(label);}host.append(el('h3',t('models')),modelHost);const grid=el('div',undefined,'report-grid'),cap=input('cap',business.policy.daily_cap||10,'number'),budget=input('budget',business.policy.daily_budget_usd||1,'number'),retention=input('retention',business.policy.retention_days||90,'number');cap.min=1;cap.max=100;budget.min=.01;budget.max=100;budget.step=.01;retention.min=1;retention.max=365;grid.append(field('cap',cap),field('budget',budget),field('retention',retention));host.append(grid);const ack=input('', '', 'checkbox'),label=el('label',undefined,'report-check');label.append(ack,el('span',t('approve')));host.append(label);const actions=el('div',undefined,'report-actions');actions.append(btn('revoke',async()=>{await api('/businesses/'+business.id+'/consent','DELETE');await reloadBusiness();$('reportDialog').close();},'danger'),btn('apply',async()=>{if(!ack.checked){ack.focus();return;}for(const n of [cap,budget,retention])if(!n.reportValidity())return;await api('/businesses/'+business.id+'/consent','PUT',{confirmed:true,models:chosen.filter(([,c])=>c.checked).map(([m])=>m),daily_cap:Number(cap.value),daily_budget_usd:Number(budget.value),retention_days:Number(retention.value)});await reloadBusiness();$('reportDialog').close();message('configured');},'primary'));host.append(actions);}
  async function reloadBusiness(){const id=business.id;businesses=(await api('/businesses')).items;business=businesses.find(b=>b.id===id)||businesses[0];}
  async function boot(){try{user=await api('/me');businesses=(await api('/businesses')).items;business=businesses[0];showApp();clearInterval(poll);poll=setInterval(()=>{if(!document.hidden&&tab==='list'&&!$('reportDialog').open)loadList().catch(e=>message(errorKey(e),true));},15000);}catch{showLogin();}}
  $('reportDialog').addEventListener('close',()=>{setTimeout(()=>{if(returnFocus?.isConnected&&!returnFocus.disabled)returnFocus.focus();else document.querySelector('#reportListItems button')?.focus();},0);});
  $('reportDialogClose').onclick=()=>$('reportDialog').close();$('reportLogout').onclick=()=>act($('reportLogout'),async()=>{if(!discard())return;await api('/logout','POST',{});showLogin();});$('loginForm').onsubmit=async e=>{e.preventDefault();const b=$('loginButton');b.disabled=true;try{await api('/login','POST',{username:$('username').value,password:$('password').value});$('password').value='';await boot();}catch{$('loginError').textContent=t('error');}finally{b.disabled=false;}};
  function loginLocale(){document.documentElement.lang=I.lang;document.documentElement.dir=['fa','ar'].includes(I.lang)?'rtl':'ltr';$('login').lang=I.lang;}
  $('loginLanguageSelect').value=I.lang;loginLocale();$('loginLanguageSelect').addEventListener('change',e=>{I.set(e.target.value);loginLocale();});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});boot();
})();
